### ISSUE TITLE
Installation Permission denied

### ISSUE THREAD

**Issue by fafafoya** [AzuraCast/AzuraCast#1878]
Trying to install Azuracast on Ubuntu 18.04:
Logged in with root
Created User: sammy
usermod -aG sudo sammy

Then logged in with sammy
Tried to install:
sudo curl -L https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh > docker.sh

I get this error:
-bash: docker.sh: Permission denied

**Comment by loz100loz** [comment]
Hey, did you find a fix for this?

**Comment by SlvrEagle23** [comment]
@loz100loz This should be fixed, as per our installation instructions, by running:
```
chmod a+x docker.sh
```
or `sudo chmod a+x docker.sh` if needed.

**Comment by IlyasMooerkens** [comment]
Hello i am getting the same error and use it on windows is that the problom?

**Comment by crispybegs** [comment]
i'm having this same problem. ubtunu (23.04). can't make it work at all. any updates?

**Comment by SofStartsFires** [comment]
Still having this issue as well. It seems like the 'fix' is on step 2, but step 1 doesn't work, so can't do step 2 without step 1 already working, no?
I just get 
"chmod: cannot access 'docker.sh': No such file or directory"
