### ISSUE TITLE
After update, new created station is not streaming

### ISSUE THREAD

**Issue by onurk7** [AzuraCast/AzuraCast#2674]
Hello

Just run an update and added a new station. Icecast and liquidsoap is not starting.

docker, ubuntu

liquidsoap logs:

> 2020/04/14 07:51:47 >>> LOG START
> 2020/04/14 07:51:47 [main:3] Liquidsoap 1.4.1
> 2020/04/14 07:51:47 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.3 sedlex=2.1 menhirLib=20200211 dtools=0.4.2 duppy=0.8.0 cry=0.6.1 mm=0.5.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.3 mad=0.4.5 flac=0.1.5 flac.ogg=0.1.5 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.3.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.9 camomile=1.0.2 faad=0.4.0
> 2020/04/14 07:51:47 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
> 2020/04/14 07:51:47 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
> 2020/04/14 07:51:47 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
> 2020/04/14 07:51:47 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
> 2020/04/14 07:51:47 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
> 2020/04/14 07:51:47 [sandbox:3] Running inside a docker container, disabling sandboxing..
> init: exception encountered during start phase:
>   Error while trying to bind server/telnet socket: Address already in use in bind()

> 2020/04/14 08:00:49 [fsafasfas_local_1:2] Connection failed: 401, Authentication Required (HTTP/1.0)
> 2020/04/14 08:00:49 [fsafasfas_local_1:3] Will try again in 3.00 sec.
> 2020/04/14 08:00:49 [lang:3] AzuraCast Raw Response: 
> 2020/04/14 08:00:49 [lang:3] AzuraCast Error: Delaying subsequent requests...
> 2020/04/14 08:00:51 [lang:3] AzuraCast Raw Response: 
> 2020/04/14 08:00:51 [lang:3] AzuraCast Error: Delaying subsequent requests...
> 2020/04/14 08:00:53 [fsafasfas_local_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
> 2020/04/14 08:00:53 [fsafasfas_local_1:2] Connection failed: 401, Authentication Required (HTTP/1.0)
> strange error flushing buffer ... 
> 2020/04/14 08:00:53 [fsafasfas_local_1:3] Will try again in 3.00 sec.
> strange error flushing buffer ... 

Icecast error logs:

> [2020-04-14  07:51:50] WARN xml/parsing skipping element "stream-description" parsing "mount" at line 27
> [2020-04-14  07:51:50] WARN xml/parsing warning: 
> [2020-04-14  07:51:50] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28

**Comment by radiolize** [comment]
I guess I've just discovered something.

The port 8120 looks like still in use even if these ports don't host a station as I see at my instance. The other stations are working but there is a problem at that ports somehow. 

I've deleted the station which stands at 8120 (Which I was created and did not start to stream and opened this issue) and then run docker-compose restart-stations and then run a command to check ports. As you will see, these ports are still in use by docker somehow and that's why icecast do not start I guess.

docker-pr   909            root    4u  IPv6 132991300      0t0  TCP *:8136 (LISTEN)
docker-pr   921            root    4u  IPv6 132989290      0t0  TCP *:8135 (LISTEN)
docker-pr   933            root    4u  IPv6 132991307      0t0  TCP *:8130 (LISTEN)
**docker-pr   947            root    4u  IPv6 132989312      0t0  TCP *:8126 (LISTEN)
docker-pr   962            root    4u  IPv6 132989319      0t0  TCP *:8125 (LISTEN)
docker-pr   976            root    4u  IPv6 132991338      0t0  TCP *:8120 (LISTEN)**

**Comment by SlvrEagle23** [comment]
@radiolize This may be relating to a previous issue (which I'm having trouble finding at the moment), but it's a long-running known issue that deleted radio stations aren't having their ports properly cleared. Restarting the `stations` container should fix the issue, but it's something we still need to look into further.

**Comment by SlvrEagle23** [comment]
@radiolize I've updated the version of supervisor we use on our `stations` image, which should completely fix this issue. In my local tests, Supervisor now correctly waits for the process to shut down before continuing, which is what was causing the issue before.

**Comment by radiolize** [comment]
Run an update on that instance. The station's broadcasting and autodj still not working after I've deleted that station stands at that port and created new one after the update. 

Liquidsoap logs:

> 2020/04/20 02:58:47 >>> LOG START
> 2020/04/20 02:58:47 [main:3] Liquidsoap 1.4.1
> 2020/04/20 02:58:47 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.3 sedlex=2.1 menhirLib=20200211 dtools=0.4.2 duppy=0.8.0 cry=0.6.1 mm=0.5.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.3 mad=0.4.5 flac=0.1.5 flac.ogg=0.1.5 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.3.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.9 camomile=1.0.2 faad=0.4.0
> 2020/04/20 02:58:47 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
> 2020/04/20 02:58:47 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
> 2020/04/20 02:58:47 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
> 2020/04/20 02:58:47 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
> 2020/04/20 02:58:47 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
> init: exception encountered during start phase:
>   Error while trying to bind server/telnet socket: Address already in use in bind()

Icecast logs:

> [2020-04-20  02:58:46] WARN xml/parsing warning: 
> [2020-04-20  02:58:46] WARN xml/parsing skipping element "stream-description" parsing "mount" at line 27
> [2020-04-20  02:58:46] WARN xml/parsing warning: 
> [2020-04-20  02:58:46] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28
> [2020-04-20  02:58:46] WARN xml/parsing warning: 
> [2020-04-20  02:58:46] WARN xml/parsing skipping element "genre" parsing "mount" at line 29

**Comment by SlvrEagle23** [comment]
@radiolize I've made further updates that should help fix this issue.

Run the routine updater, and then afterwards, any newly deleted stations should properly clear up their port assignments during their shutdown process.
