### ISSUE TITLE
AzuraCast Stream URL Issue

### ISSUE THREAD

**Issue by esmondgh** [AzuraCast/AzuraCast#2969]
Using Docker installation method:
**Yes**

Host Operating System:
**Ubuntu 18.04**

AzuraCast Version:
**0.10.2**

**Description:**
On May 8, 2020, I install AzuraCast v0.10.2 and both URLs were working.
**Working:** https://my-stream-url/radio/8000/stream.mp3
**Working:** https://my-stream-url:8000/stream.mp3

On June 19, 2020, After an update.
**Working:** https://my-stream-url/radio/8000/stream.mp3
**Not Working:** https://my-stream-url:8000/stream.mp3

**Comment by CouinCouin** [comment]
Hi, 

I encounter the same problem (since today, info reported by a member of the webradio) but I didn't updated AzuraCast (still  v0.9.9, #835968d (2020-04-25 7:28) version ).
One of my mountpoints : 
https://stream-eurodance90.fr:8000/64.aac

If I past stream link in Firefox , I get : 

> Échec de la connexion sécurisée
> Une erreur est survenue pendant une connexion à stream-eurodance90.fr:8000. PR_END_OF_FILE_ERROR

On Chrome : 

> Ce site est inaccessiblestream-eurodance90.fr a mis fin à la connexion de manière inattendue.
> Voici quelques conseils :
> Vérifier la connexion
> Vérifier le proxy et le pare-feu
> Exécutez les diagnostics réseau de Windows
> ERR_CONNECTION_CLOSED

(Sorry for french messages of the browsers).

Thanks :)

**Comment by SlvrEagle23** [comment]
@esmondgh @CouinCouin This HTTPS issue with Icecast was caused by our recent changes implementing the Nginx proxy service with its own automated LetsEncrypt setup.

I've updated our Icecast configuration generator to look for the certificates that are generated/managed by the nginx proxy, so your HTTPS connections to the direct ports of your stations should now be working properly and automatically once again.

**Comment by CouinCouin** [comment]
Hi

thanks for explanation, but when theese recent changes has been implemented ?  

Our server installation dates from April 25 2020, and we didn't update it. 

Is there some hidden automatic (partial) updates ?

**Comment by SlvrEagle23** [comment]
@CouinCouin There are no automated updates; you should follow our [update instructions](https://www.azuracast.com/administration/system/updating.html) to update to the latest version which includes the fixes.

**Comment by CouinCouin** [comment]
Hi, Thanks, but what I mean in my previous post is "how it was ok before and not afgter, even we  never updated azuracast since instalaltion of April 25 ?"  :)

**Comment by esmondgh** [comment]
After the update, the URL is still not working.
**AzuraCast • v0.10.3, #9811fbb (2020-06-22 4:38)**

**Working**: https://my-stream-url/radio/8000/stream.mp3
**Still not working**: https://my-stream-url:8000/stream.mp3

**Comment by SlvrEagle23** [comment]
@esmondgh What error are you seeing when visiting the direct port URL? Are you updating your `docker-compose.yml` file when prompted to by the updater?

**Comment by esmondgh** [comment]
Concerning the update, I use:

**cd /var/azuracast
./docker.sh update-self
yes "" | ./docker.sh update**

When I visit the direct port URL, I get: below error.
![error](https://user-images.githubusercontent.com/42568091/86259061-12f3f100-bbab-11ea-9027-d6a912a85862.jpg)

**Comment by SlvrEagle23** [comment]
@esmondgh Do you have LetsEncrypt set up on your main host? Do you have multiple hosts, etc. by chance? There may be an edge case that's causing this problem.

**Comment by esmondgh** [comment]
AzuraCast is the only script running on this server and yes I have LetsEncrypt set up on my main host.
It's running on a subdomain, HTTP port 80 and HTTPS port 1099.
Site Base URL looks like this: https://stream.example.com:1099

**_Prefer stable release versions of AzuraCast? [y/N] y
Customize AzuraCast ports? [y/N] y
Port to use for HTTP connections [80]: 80
Port to use for HTTPS connections [443]: 1099
Port to use for SFTP connections [2022]: 2022
Set up LetsEncrypt? [y/N] y_**

Installation completed successfully with no errors.
AzuraCast • v0.10.3, #9811fbb (2020-06-22 4:38)

**Comment by SlvrEagle23** [comment]
@esmondgh Oh, you have LetsEncrypt on the host, but not set up inside AzuraCast itself? That may be the issue then...it's looking for a valid SSL certificate among the certs provided to it via AzuraCast's own SSL cert storage. While nginx will accept the self-signed default certificate, Icecast won't because it's stricter about it.

**Comment by esmondgh** [comment]
LetsEncrypt was set up during AzurzCast Installation when I was asked **Set up LetsEncrypt? [y/N]**
I also provided a domain name which AzuraCast will use and email address.

Its a valid SSL certificate which is why the below URL is working but not the direct port URL.

**Working**: https://my-stream-url/radio/8000/stream.mp3
**Not working**: https://my-stream-url:8000/stream.mp3

**Comment by SlvrEagle23** [comment]
@esmondgh I understand, but I don't know why this issue is continuing to happen even after the latest updates on your installation. I don't have any further insight into this problem now, so there's no further support I can provide. I'm sorry for the inconvenience.

**Comment by esmondgh** [comment]
I found below warning In **/var/lib/docker/volumes/azuracast_station_data/_data/station_name/config/icecast.log** 

[2020-07-11  04:59:15] WARN xml/parsing warning: 
[2020-07-11  04:59:15] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28
[2020-07-11  04:59:15] WARN connection/get_ssl_certificate Invalid cert file /etc/nginx/ssl/ssl.crt (system lib)
[2020-07-11  04:59:15] WARN slave/slave_startup process has 65536 max file descriptor limit

**Comment by SlvrEagle23** [comment]
@esmondgh I'm looking at our CertificateLocator class and it never returns `/etc/nginx/ssl/ssl.crt`. I'm not sure why it would be instructing your Icecast installation to look there for its cert...
