### ISSUE TITLE
Can't update. Stuck on Node Dependencies

### ISSUE THREAD

**Issue by NicoxDJ** [AzuraCast/AzuraCast#3028]
**Using Docker installation method**
No

**AzuraCast version**
v0.10.3

**Host Operating System**
Ubuntu 18.04.4 LTS on Raspberry Pi 3B+

**Describe the bug**
I saw that you have a lot of new things so i hit update.sh
Everything was fine till the step with Pull Node Dependencies. Than i've got this Error: https://pastebin.com/uNRiFRGF
And the update process is stopped :( I tried multiple times, its always the same. Apparently something is missing in the packages. Now i can't do anything on the dashboard, because all scripts and css are missing :(

**Comment by Vaalyn** [comment]
It looks like `node-sass` does not publish arm64 releases yet. See https://github.com/sass/node-sass/issues/2667 and https://github.com/sass/node-sass/pull/2647

This problem seems to exist due to the switch from pre-compiled static assets to running the build process on updates. See https://github.com/AzuraCast/AzuraCast/commit/12df780eb731b81583098f9a5072efaec1983e73#diff-acb48186228008786d784b08a7306c5d and https://github.com/AzuraCast/AzuraCast/commit/628f978324d3c108bb9aa8690dbbf140abb8b528

I think in order to solve this issue we'd need to [compile `node-sass`](https://github.com/sass/node-sass#rebuilding-binaries) on arm64 ansible installations.

**Comment by NicoxDJ** [comment]
@Vaalyn I see. Please, keep me in touch, when it's ready.

**Comment by NicoxDJ** [comment]
@Vaalyn is there anyway i can bring the old version? I notice too that the server is going too overload now.

**Comment by Vaalyn** [comment]
If you have a backup from the version before the update you could use that one to restore it.

**Comment by NicoxDJ** [comment]
@Vaalyn unfortunately i don't :( I forgot to do. I was hoping that the update will be for good. I found in old branches the files needed (css, js, etc.), but now i can't run the controllers properly. Its always 500 Internal Error. I removed the vendor folder and install the application again, but still nothing.

**Comment by Vaalyn** [comment]
Keep in mind that I don't really know much about ansible and our ansible pipeline and that this is unsupported. So I have no idea if this will work but from what I can tell you could disable the ansible tasks steps for building the frontend assets by commenting them with a `#` in the beginning of the lines I marked here: https://github.com/AzuraCast/AzuraCast/blob/master/util/ansible/roles/azuracast-build/tasks/main.yml#L15-L27

I think this should let you skip the step that seems to be failing.

**Comment by NicoxDJ** [comment]
> Keep in mind that I don't really know much about ansible and our ansible pipeline and that this is unsupported. So I have no idea if this will work but from what I can tell you could disable the ansible tasks steps for building the frontend assets by commenting them with a `#` in the beginning of the lines I marked here: https://github.com/AzuraCast/AzuraCast/blob/master/util/ansible/roles/azuracast-build/tasks/main.yml#L15-L27
> 
> I think this should let you skip the step that seems to be failing.

@Vaalyn well, it worked. It finish the process. But it's still 500 Internal Error. Actually when i hit the dashboard, it gives me the login page, and after login,  than its 500 Internal Error. There isn't anything about that on php and nginx logs :(

**Comment by Vaalyn** [comment]
Not really sure what's going on there.
You could try this here: https://www.azuracast.com/help/ansible/#force-a-full-update

**Comment by NicoxDJ** [comment]
Well, after 4th try i've got:
```
TASK [azuracast-radio : Initialize OPAM - This takes a while...] ************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "opam init -a --disable-sandboxing --bare && opam switch create 4.08.0", "delta": "0:09:23.427358", "end": "2020-07-27 16:32:06.656635", "msg": "non-zero return code", "rc": -9, "start": "2020-07-27 16:22:43.229277", "stderr": "[NOTE] Will configure from built-in defaults.\n[NOTE] Make sure that ~/.bash_profile is well sourced in your ~/.bashrc.", "stderr_lines": ["[NOTE] Will configure from built-in defaults.", "[NOTE] Make sure that ~/.bash_profile is well sourced in your ~/.bashrc."], "stdout": "Checking for available remotes: rsync and local, git.\n  - you won't be able to use mercurial repositories unless you install the hg command on your system.\n  - you won't be able to use darcs repositories unless you install the darcs command on your system.\n\n\n<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><><><>\n[default] Initialised\n\nUser configuration:\n  ~/.bash_profile is already up-to-date.\n\n<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>\n[ocaml-base-compiler.4.08.0] downloaded from cache at https://opam.ocaml.org/cache", "stdout_lines": ["Checking for available remotes: rsync and local, git.", "  - you won't be able to use mercurial repositories unless you install the hg command on your system.", "  - you won't be able to use darcs repositories unless you install the darcs command on your system.", "", "", "<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><><><>", "[default] Initialised", "", "User configuration:", "  ~/.bash_profile is already up-to-date.", "", "<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>", "[ocaml-base-compiler.4.08.0] downloaded from cache at https://opam.ocaml.org/cache"]}
```

The rest i've got: `ERROR! A worker was found in a dead state`

**Comment by NicoxDJ** [comment]
After the last git pull, i think i have better handling of the Server errors.
Now i've got
```
500
Library InlinePlayer not found!
Assets.php : 183
```

**Comment by NicoxDJ** [comment]
Again some fixes, debugging. I installed VM with azuracast, i copied all vendors and static folders. (BTW, brand new install on VM doesn't finish correctly too. There are errors on "Run AzuraCast Setup" install and update too) 
Now i've reach some point, that liquidsoap can't work:
```
Liquidsoap encountered an error
main:2] We must catchup 3.27 seconds!
2020/07/27 15:36:47 [clock.wallclock_main:2] We must catchup 1.03 seconds!
2020/07/27 15:36:48 [clock.wallclock_main:2] We must catchup 1.03 seconds!
2020/07/27 15:36:48 [club-bg_next_song:3] Prepared "/media/Music/The Voice/REMIXES/Miley Cyrus - Wrecking Ball (CAKED UP Remix).mp3" (RID 1).
2020/07/27 15:36:51 [cross_7784:3] Analysis: -72.330713dB / -25.326440dB (7.50s / 7.54s)
2020/07/27 15:36:51 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
```
I tried to delete that song from the playlist, not worked. I tried to delete the whole playlist, not worked too.

**Comment by SlvrEagle23** [comment]
@NicoxDJ @Vaalyn I've switched our Node dependencies away from node-sass to the Dart-based `sass` package, which is recommended by several packages (including `sass-loader`) as a very suitable alternative to node-sass without nearly as many binary dependencies.

Hopefully this will have much more fluid support for ARM64, and will bring us back into active support for Raspberry Pi type devices. Update and let me know how it goes.

**Comment by blindndangerous** [comment]
I just installed Ubuntu 20 on a pi4 and tried to install azuracast.  When I try, I get Node-sass can't install.  Was the install script changed for dart-sass?  I think it's still trying to get the other one.

**Comment by SlvrEagle23** [comment]
@blindndangerous Yes, it should have fully switched out from node-sass to dart-sass, which is a JS-native library that should have no binaries to load on any platform.

**Comment by blindndangerous** [comment]
> @blindndangerous Yes, it should have fully switched out from node-sass to dart-sass, which is a JS-native library that should have no binaries to load on any platform.

Odd that mine didn't.  
Task azuracast-build: Pull Node Dependencies.
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "npm ci", "delta": "0:00
:43.944424", "end": "2020-08-31 00:19:45.997216", "msg": "non-zero return code",
2 space  "rc": 1, "start": "2020-08-31 00:19:02.052792", "stderr": "npm WARN prepare removing existing node_modules/ before installation\nCannot download \"https://github.com/sass/node-sass/releases/download/v4.14.1/linux-arm64-72_binding.node\": \
Anything I can check or do?

**Comment by SlvrEagle23** [comment]
@blindndangerous Did you pull from the Github repo fresh, or is this running install on an older codebase?

If you run `git reset --hard && git pull` in the document root, it'll update it to the latest rolling release.

**Comment by blindndangerous** [comment]
@SlvrEagle23 This was a fresh install. Installed ubuntu, made the www directory, and git cloned.  I'll give that a try and see what happens.

**Comment by SlvrEagle23** [comment]
@blindndangerous Never mind, found another package that still depends on node-sass and is still requiring it. Will work on removing it entirely out of our little stack.

**Comment by SlvrEagle23** [comment]
@blindndangerous Should be gone now; update to the latest version (using the command from the previous reply) and there should be no issues with it as a dependency.

**Comment by blindndangerous** [comment]
@SlvrEagle23 Ok, that error is fixed, however now I'm getting another one about the migration failing during post checks.  It says to run sync-metadata-storage.  Any idea on this one?

**Comment by SlvrEagle23** [comment]
@blindndangerous No idea on that one. Likely unrelated from the first error.

**Comment by NicoxDJ** [comment]
@SlvrEagle23 I did the git reset --hard, and than i hit the update.sh

Stuck here:
```
TASK [azuracast-build : Build AzuraCast Frontend Scripts] *******************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "npm run build", "delta": "0:02:10.813987", "end": "2020-08-31 12:40:44.121042", "msg": "non-zero return code", "rc": 137, "start": "2020-08-31 12:38:33.307055", "stderr": "(node:15806) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.\nKilled\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 137\nnpm ERR! azuracast@ build: `gulp`\nnpm ERR! Exit status 137\nnpm ERR! \nnpm ERR! Failed at the azuracast@ build script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /var/azuracast/.npm/_logs/2020-08-31T09_40_42_715Z-debug.log", "stderr_lines": ["(node:15806) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.", "Killed", "npm ERR! code ELIFECYCLE", "npm ERR! errno 137", "npm ERR! azuracast@ build: `gulp`", "npm ERR! Exit status 137", "npm ERR! ", "npm ERR! Failed at the azuracast@ build script.", "npm ERR! This is probably not a problem with npm. There is likely additional logging output above.", "", "npm ERR! A complete log of this run can be found in:", "npm ERR!     /var/azuracast/.npm/_logs/2020-08-31T09_40_42_715Z-debug.log"], "stdout": "\n> azuracast@ build /var/azuracast/www/frontend\n> gulp\n\n[12:38:44] Using gulpfile ~/www/frontend/gulpfile.js\n[12:38:44] Starting 'default'...\n[12:38:44] Starting 'clean'...\n[12:38:44] Finished 'clean' after 331 ms\n[12:38:44] Starting 'concat-js'...\n[12:38:44] Starting 'build-vue'...\n[12:38:44] Starting 'build-js'...\n[12:38:44] Starting 'build-css'...\n[12:38:44] Starting 'bundle_deps'...\n[12:38:48] Starting 'scripts:jquery'...\n[12:38:48] Starting 'scripts:vue'...\n[12:38:48] Starting 'scripts:lodash'...\n[12:38:48] Starting 'scripts:bootstrap'...\n[12:38:48] Starting 'scripts:bootstrap-notify'...\n[12:38:48] Starting 'scripts:sweetalert'...\n[12:38:48] Starting 'scripts:autosize'...\n[12:38:48] Starting 'scripts:material-icons'...\n[12:38:48] Starting 'scripts:roboto-fontface'...\n[12:38:48] Starting 'scripts:dirrty'...\n[12:38:48] Starting 'scripts:store'...\n[12:38:48] Starting 'scripts:zxcvbn'...\n[12:38:48] Starting 'scripts:chartjs'...\n[12:38:48] Starting 'scripts:chosen'...\n[12:38:48] Starting 'scripts:moment'...\n[12:38:48] Starting 'scripts:moment-timezone'...\n[12:38:48] Starting 'scripts:daterangepicker'...\n[12:38:48] Starting 'scripts:codemirror'...\n[12:38:48] Starting 'scripts:clipboard'...\n[12:38:48] Starting 'scripts:fancybox'...\n[12:38:48] Starting 'scripts:flowjs'...\n[12:38:48] Starting 'scripts:leaflet'...\n[12:38:48] Starting 'scripts:leaflet-fullscreen'...\n[12:38:48] Starting 'scripts:nchan'...\n[12:38:48] Starting 'scripts:webcaster'...\n[12:38:48] Starting 'scripts:bootgrid'...\n[12:38:48] Starting 'scripts:bootstrap-vue'...\n[12:39:52] Finished 'scripts:zxcvbn' after 1.05 min\n[12:39:52] Finished 'scripts:jquery' after 1.05 min\n[12:39:52] Finished 'scripts:lodash' after 1.05 min\n[12:39:52] Finished 'scripts:bootstrap' after 1.05 min\n[12:39:52] Finished 'scripts:bootstrap-notify' after 1.05 min\n[12:39:52] Finished 'scripts:sweetalert' after 1.05 min\n[12:39:52] Finished 'scripts:autosize' after 1.05 min\n[12:39:52] Finished 'scripts:dirrty' after 1.05 min\n[12:39:52] Finished 'scripts:store' after 1.05 min\n[12:39:52] Finished 'scripts:clipboard' after 1.05 min\n[12:39:52] Finished 'scripts:moment-timezone' after 1.05 min\n[12:39:52] Finished 'scripts:nchan' after 1.05 min\n[12:39:52] Finished 'scripts:flowjs' after 1.05 min\n[12:39:52] Finished 'scripts:bootgrid' after 1.05 min\n[12:39:52] Finished 'scripts:bootstrap-vue' after 1.05 min\n[12:39:52] Finished 'build-css' after 1.12 min\n[12:39:52] Finished 'concat-js' after 1.12 min\n[12:39:52] Finished 'scripts:vue' after 1.05 min\n[12:39:53] Finished 'scripts:fancybox' after 1.07 min\n[12:39:53] Finished 'scripts:moment' after 1.07 min\n[12:39:53] Finished 'scripts:daterangepicker' after 1.07 min\n[12:39:53] Finished 'build-js' after 1.13 min\n[12:39:53] Finished 'scripts:chartjs' after 1.07 min\n[12:39:53] Finished 'scripts:codemirror' after 1.07 min\n[12:39:58] Finished 'scripts:webcaster' after 1.17 min\n[12:39:59] Finished 'scripts:chosen' after 1.17 min\n[12:39:59] Finished 'scripts:leaflet-fullscreen' after 1.17 min\n[12:40:10] Finished 'scripts:leaflet' after 1.35 min\n[12:40:10] Finished 'scripts:material-icons' after 1.35 min\n[12:40:30] Finished 'scripts:roboto-fontface' after 1.68 min\n[12:40:30] Finished 'bundle_deps' after 1.75 min", "stdout_lines": ["", "> azuracast@ build /var/azuracast/www/frontend", "> gulp", "", "[12:38:44] Using gulpfile ~/www/frontend/gulpfile.js", "[12:38:44] Starting 'default'...", "[12:38:44] Starting 'clean'...", "[12:38:44] Finished 'clean' after 331 ms", "[12:38:44] Starting 'concat-js'...", "[12:38:44] Starting 'build-vue'...", "[12:38:44] Starting 'build-js'...", "[12:38:44] Starting 'build-css'...", "[12:38:44] Starting 'bundle_deps'...", "[12:38:48] Starting 'scripts:jquery'...", "[12:38:48] Starting 'scripts:vue'...", "[12:38:48] Starting 'scripts:lodash'...", "[12:38:48] Starting 'scripts:bootstrap'...", "[12:38:48] Starting 'scripts:bootstrap-notify'...", "[12:38:48] Starting 'scripts:sweetalert'...", "[12:38:48] Starting 'scripts:autosize'...", "[12:38:48] Starting 'scripts:material-icons'...", "[12:38:48] Starting 'scripts:roboto-fontface'...", "[12:38:48] Starting 'scripts:dirrty'...", "[12:38:48] Starting 'scripts:store'...", "[12:38:48] Starting 'scripts:zxcvbn'...", "[12:38:48] Starting 'scripts:chartjs'...", "[12:38:48] Starting 'scripts:chosen'...", "[12:38:48] Starting 'scripts:moment'...", "[12:38:48] Starting 'scripts:moment-timezone'...", "[12:38:48] Starting 'scripts:daterangepicker'...", "[12:38:48] Starting 'scripts:codemirror'...", "[12:38:48] Starting 'scripts:clipboard'...", "[12:38:48] Starting 'scripts:fancybox'...", "[12:38:48] Starting 'scripts:flowjs'...", "[12:38:48] Starting 'scripts:leaflet'...", "[12:38:48] Starting 'scripts:leaflet-fullscreen'...", "[12:38:48] Starting 'scripts:nchan'...", "[12:38:48] Starting 'scripts:webcaster'...", "[12:38:48] Starting 'scripts:bootgrid'...", "[12:38:48] Starting 'scripts:bootstrap-vue'...", "[12:39:52] Finished 'scripts:zxcvbn' after 1.05 min", "[12:39:52] Finished 'scripts:jquery' after 1.05 min", "[12:39:52] Finished 'scripts:lodash' after 1.05 min", "[12:39:52] Finished 'scripts:bootstrap' after 1.05 min", "[12:39:52] Finished 'scripts:bootstrap-notify' after 1.05 min", "[12:39:52] Finished 'scripts:sweetalert' after 1.05 min", "[12:39:52] Finished 'scripts:autosize' after 1.05 min", "[12:39:52] Finished 'scripts:dirrty' after 1.05 min", "[12:39:52] Finished 'scripts:store' after 1.05 min", "[12:39:52] Finished 'scripts:clipboard' after 1.05 min", "[12:39:52] Finished 'scripts:moment-timezone' after 1.05 min", "[12:39:52] Finished 'scripts:nchan' after 1.05 min", "[12:39:52] Finished 'scripts:flowjs' after 1.05 min", "[12:39:52] Finished 'scripts:bootgrid' after 1.05 min", "[12:39:52] Finished 'scripts:bootstrap-vue' after 1.05 min", "[12:39:52] Finished 'build-css' after 1.12 min", "[12:39:52] Finished 'concat-js' after 1.12 min", "[12:39:52] Finished 'scripts:vue' after 1.05 min", "[12:39:53] Finished 'scripts:fancybox' after 1.07 min", "[12:39:53] Finished 'scripts:moment' after 1.07 min", "[12:39:53] Finished 'scripts:daterangepicker' after 1.07 min", "[12:39:53] Finished 'build-js' after 1.13 min", "[12:39:53] Finished 'scripts:chartjs' after 1.07 min", "[12:39:53] Finished 'scripts:codemirror' after 1.07 min", "[12:39:58] Finished 'scripts:webcaster' after 1.17 min", "[12:39:59] Finished 'scripts:chosen' after 1.17 min", "[12:39:59] Finished 'scripts:leaflet-fullscreen' after 1.17 min", "[12:40:10] Finished 'scripts:leaflet' after 1.35 min", "[12:40:10] Finished 'scripts:material-icons' after 1.35 min", "[12:40:30] Finished 'scripts:roboto-fontface' after 1.68 min", "[12:40:30] Finished 'bundle_deps' after 1.75 min"]}
```

**Comment by SlvrEagle23** [comment]
@NicoxDJ I'm looking up that error and it appears to be down to a lack of available memory. You may want to try [creating a swap space](https://linuxize.com/post/how-to-add-swap-space-on-ubuntu-20-04/) to handle some of the memory overload.

**Comment by NicoxDJ** [comment]
@SlvrEagle23 yey,
```
PLAY RECAP **************************************************************************************************************
localhost                  : ok=21   changed=10   unreachable=0    failed=0    skipped=76   rescued=0    ignored=0  
```
And after all, i still have problem with the liquidsoap, like this here: https://github.com/AzuraCast/AzuraCast/issues/3028#issuecomment-675653780
```
Liquidsoap encountered an error
main:2] We must catchup 3.27 seconds!
2020/07/27 15:36:47 [clock.wallclock_main:2] We must catchup 1.03 seconds!
2020/07/27 15:36:48 [clock.wallclock_main:2] We must catchup 1.03 seconds!
2020/07/27 15:36:48 [club-bg_next_song:3] Prepared "/media/Music/The Voice/REMIXES/Miley Cyrus - Wrecking Ball (CAKED UP Remix).mp3" (RID 1).
2020/07/27 15:36:51 [cross_7784:3] Analysis: -72.330713dB / -25.326440dB (7.50s / 7.54s)
2020/07/27 15:36:51 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
```
The playlist that is containing this song is already deleted, but still somethings bothering the liquidsoap. Is there a way i can reset the liquid soap memory?

**Comment by SlvrEagle23** [comment]
@NicoxDJ you can restart the station via "Utilities" > "Restart Broadcasting".

**Comment by NicoxDJ** [comment]
@SlvrEagle23 nope, the same error is showing while hit start of AutoDJ. Its like didn't flush the liquidsoap buffer at all :(

**Comment by SlvrEagle23** [comment]
@NicoxDJ Do you see an error in the web log (or the AzuraCast application log) from the log viewer?

**Comment by SlvrEagle23** [comment]
Update: I bought a Raspberry Pi 4 (thanks for your donation support, friends) so I could test ARM64 integration of AzuraCast, and I'm noticing that the Ansible installation can't make it any farther than rebooting the `redis` service because on my instance of Ubuntu 20.04 the service name is `redis-server` instead.

Has anyone else noticed this issue?

**Comment by blindndangerous** [comment]
@SlvrEagle23 Yep, I have. Sorry, I meant to open an issue about it. I haven't been able to get past it, as if I get to that point, do sudo systemctl start redis-server and try running install.sh again, I get the sync-metadata-storage issue I mentioned earlier.

**Comment by NicoxDJ** [comment]
@SlvrEagle23 Yes, i can see the error log from the dashboard, but its still the same. It's not updating anymore. And every time i try to start the liuqidsoap it shows the last lines.
And yes, i have heard about differs from 18.04 and 20.04, thats why i install 18.04 on my RBP3B+

**Comment by NicoxDJ** [comment]
@SlvrEagle23 I'm pretty much sure, that the liquidsoap is uninstalled. I try to install it with apt-get install, but somehow it doesn't start again :( Is there anyway i can force only your liquidsoap installation?

**Comment by SlvrEagle23** [comment]
@NicoxDJ Our installation isn't managed via the apt package manager, it's managed via the OCaml `OPAM` package manager instead; you should remove any Liquidsoap instance installed via apt and then re-run the updater in full mode, i.e.:

```bash
./update.sh --full
```

**Comment by NicoxDJ** [comment]
@SlvrEagle23 
OK, i think some things were reinstalled, but something happened with Redis now :(
```
TASK [redis : Add Redis PPA repository] ****************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "apt-key adv --recv-keys --no-tty --keyserver hkp://keyserver.ubuntu.com:80 136221EE520DDFAF0A905689B9316A7BC7917B12", "msg": "Warning: apt-key output should not be parsed (stdout is not a terminal)\ngpg: key B9316A7BC7917B12: public key \"Launchpad chrislea\" imported\ngpg: can't connect to the agent: IPC connect call failed\ngpg: Total number processed: 1\ngpg:               imported: 1", "rc": 2, "stderr": "Warning: apt-key output should not be parsed (stdout is not a terminal)\ngpg: key B9316A7BC7917B12: public key \"Launchpad chrislea\" imported\ngpg: can't connect to the agent: IPC connect call failed\ngpg: Total number processed: 1\ngpg:               imported: 1\n", "stderr_lines": ["Warning: apt-key output should not be parsed (stdout is not a terminal)", "gpg: key B9316A7BC7917B12: public key \"Launchpad chrislea\" imported", "gpg: can't connect to the agent: IPC connect call failed", "gpg: Total number processed: 1", "gpg:               imported: 1"], "stdout": "Executing: /tmp/apt-key-gpghome.eh1jfSsBzQ/gpg.1.sh --recv-keys --no-tty --keyserver hkp://keyserver.ubuntu.com:80 136221EE520DDFAF0A905689B9316A7BC7917B12\n", "stdout_lines": ["Executing: /tmp/apt-key-gpghome.eh1jfSsBzQ/gpg.1.sh --recv-keys --no-tty --keyserver hkp://keyserver.ubuntu.com:80 136221EE520DDFAF0A905689B9316A7BC7917B12"]}
```

**Comment by SlvrEagle23** [comment]
@NicoxDJ I'm not sure what's happening in this case. You did create the swap space partition, right? I have a Raspberry Pi 3B that's running a brand new AzuraCast installation with no issues, but it definitely needed the swap space added first.

**Comment by NicoxDJ** [comment]
@SlvrEagle23 Yes, after i did the swap, everything were updated successfully, except the liquidsoap. Now with the --full tag, i think the liquidsoap were reinstalled too, but now something with Redis is happening :(
```
TASK [azuracast-radio : Add OPAM/OCaml Repository] *****************************************************************************************
ok: [localhost]

TASK [azuracast-radio : Install Liquidsoap Dependencies] ***********************************************************************************
ok: [localhost]

TASK [azuracast-radio : Initialize OPAM (Bionic)] ******************************************************************************************
changed: [localhost]

TASK [azuracast-radio : Initialize OPAM (Focal)] *******************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Build and Install Liquidsoap and Dependencies] *********************************************************************
changed: [localhost]

TASK [azuracast-radio : Check on Liquidsoap Installation] **********************************************************************************
FAILED - RETRYING: Check on Liquidsoap Installation (60 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (59 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (58 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (57 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (56 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (55 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (54 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (53 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (52 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (51 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (50 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (49 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (48 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (47 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (46 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (45 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (44 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (43 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (42 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (41 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (40 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (39 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (38 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (37 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (36 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (35 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (34 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (33 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (32 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (31 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (30 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (29 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (28 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (27 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (26 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (25 retries left).
changed: [localhost]

TASK [azuracast-radio : Link Liquidsoap binary (Xenial/Bionic)] ****************************************************************************
ok: [localhost]

TASK [azuracast-radio : Link Liquidsoap binary (Focal)] ************************************************************************************
skipping: [localhost]
```

**Comment by NicoxDJ** [comment]
@SlvrEagle23 Something really is happening with this Liquidsoap installation:

```
TASK [azuracast-radio : Check on Liquidsoap Installation] **********************************************************************************
FAILED - RETRYING: Check on Liquidsoap Installation (60 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (59 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (58 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (57 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (56 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (55 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (54 retries left).
FAILED - RETRYING: Check on Liquidsoap Installation (53 retries left).
fatal: [localhost]: FAILED! => {"ansible_job_id": "276293575909.22148", "attempts": 9, "changed": true, "cmd": "opam install -y samplerate.0.1.4 taglib.0.3.3 mad.0.4.5 faad.0.4.0 fdkaac.0.3.1 lame.0.3.3 vorbis.0.7.1 cry.0.6.1 flac.0.1.5 opus.0.1.3 duppy.0.8.0 ssl liquidsoap.1.4.2", "delta": "5:50:34.226205", "end": "2020-09-16 01:34:47.881167", "finished": 1, "msg": "non-zero return code", "rc": 137, "start": "2020-09-15 19:44:13.654962", "stderr": "Killed", "stderr_lines": ["Killed"], "stdout": "The following actions will be performed:\n  ∗ install conf-m4                 1        [required by ocamlfind]\n  ∗ install conf-pkg-config         1.3      [required by taglib]\n  ∗ install ocamlbuild              0.14.0   [required by uchar]\n  ∗ install dune                    2.7.1    [required by ssl]\n  ∗ install ocamlfind               1.8.1    [required by taglib, opus, liquidsoap, etc.]\n  ∗ install conf-libssl             2        [required by ssl]\n  ∗ install conf-libpcre            1        [required by pcre]\n  ∗ install uchar                   0.0.2    [required by sedlex]\n  ∗ install result                  1.5      [required by dune-configurator, ocaml-migrate-parsetree]\n  ∗ install ppx_derivers            1.2.1    [required by ocaml-migrate-parsetree]\n  ∗ install menhirSdk               20200624 [required by menhir]\n  ∗ install menhirLib               20200624 [required by menhir]\n  ∗ install dtools                  0.4.2    [required by liquidsoap]\n  ∗ install camomile                1.0.2    [required by liquidsoap]\n  ∗ install taglib                  0.3.3\n  ∗ install samplerate              0.1.4\n  ∗ install ogg                     0.5.2    [required by opus, flac, liquidsoap, vorbis]\n  ∗ install mad                     0.4.5\n  ∗ install lame                    0.3.3\n  ∗ install fdkaac                  0.3.1\n  ∗ install base-bytes              base     [required by faad]\n  ∗ install csexp                   1.3.1    [required by dune-configurator]\n  ∗ install ocaml-migrate-parsetree 1.7.3    [required by sedlex]\n  ∗ install menhir                  20200624 [required by liquidsoap]\n  ∗ install vorbis                  0.7.1\n  ∗ install opus                    0.1.3\n  ∗ install flac                    0.1.5\n  ∗ install mm                      0.5.0    [required by liquidsoap]\n  ∗ install faad                    0.4.0\n  ∗ install dune-configurator       2.7.1    [required by ssl]\n  ∗ install ppx_tools_versioned     5.4.0    [required by sedlex]\n  ∗ install ssl                     0.5.9\n  ∗ install pcre                    7.4.6    [required by duppy, liquidsoap]\n  ∗ install gen                     0.5.3    [required by sedlex]\n  ∗ install cry                     0.6.1\n  ∗ install duppy                   0.8.0\n  ∗ install sedlex                  2.2      [required by liquidsoap]\n  ∗ install liquidsoap              1.4.2\n===== ∗ 38 =====\n\n<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>\n[csexp.1.3.1] downloaded from cache at https://opam.ocaml.org/cache\n[cry.0.6.1] downloaded from cache at https://opam.ocaml.org/cache\n[dtools.0.4.2] downloaded from cache at https://opam.ocaml.org/cache\n[camomile.1.0.2] downloaded from cache at https://opam.ocaml.org/cache\n[dune.2.7.1] downloaded from cache at https://opam.ocaml.org/cache\n[dune-configurator.2.7.1] downloaded from cache at https://opam.ocaml.org/cache\n[duppy.0.8.0] downloaded from cache at https://opam.ocaml.org/cache\n[faad.0.4.0] downloaded from cache at https://opam.ocaml.org/cache\n[fdkaac.0.3.1] downloaded from cache at https://opam.ocaml.org/cache\n[gen.0.5.3] downloaded from cache at https://opam.ocaml.org/cache\n[flac.0.1.5] downloaded from cache at https://opam.ocaml.org/cache\n[lame.0.3.3] downloaded from cache at https://opam.ocaml.org/cache\n[mad.0.4.5] downloaded from cache at https://opam.ocaml.org/cache\n[liquidsoap.1.4.2] downloaded from cache at https://opam.ocaml.org/cache\n[menhir.20200624] downloaded from cache at https://opam.ocaml.org/cache\n[menhirSdk.20200624] found in cache\n[mm.0.5.0] downloaded from cache at https://opam.ocaml.org/cache\n[menhirLib.20200624] downloaded from cache at https://opam.ocaml.org/cache\n[ocaml-migrate-parsetree.1.7.3] downloaded from cache at https://opam.ocaml.org/cache\n[ocamlbuild.0.14.0] downloaded from cache at https://opam.ocaml.org/cache\n[ocamlfind.1.8.1] downloaded from cache at https://opam.ocaml.org/cache\n[ogg.0.5.2] downloaded from cache at https://opam.ocaml.org/cache\n[opus.0.1.3] downloaded from cache at https://opam.ocaml.org/cache\n[pcre.7.4.6] downloaded from cache at https://opam.ocaml.org/cache\n[ppx_derivers.1.2.1] downloaded from cache at https://opam.ocaml.org/cache\n[result.1.5] downloaded from cache at https://opam.ocaml.org/cache\n[ppx_tools_versioned.5.4.0] downloaded from cache at https://opam.ocaml.org/cache\n[samplerate.0.1.4] downloaded from cache at https://opam.ocaml.org/cache\n[ssl.0.5.9] downloaded from cache at https://opam.ocaml.org/cache\n[sedlex.2.2] downloaded from cache at https://opam.ocaml.org/cache\n[taglib.0.3.3] downloaded from cache at https://opam.ocaml.org/cache\n[uchar.0.0.2] downloaded from cache at https://opam.ocaml.org/cache\n[vorbis.0.7.1] downloaded from cache at https://opam.ocaml.org/cache\n\n<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>\n∗ installed conf-m4.1\n∗ installed conf-pkg-config.1.3\n∗ installed conf-libpcre.1\n∗ installed conf-libssl.2\n∗ installed ocamlfind.1.8.1", "stdout_lines": ["The following actions will be performed:", "  ∗ install conf-m4                 1        [required by ocamlfind]", "  ∗ install conf-pkg-config         1.3      [required by taglib]", "  ∗ install ocamlbuild              0.14.0   [required by uchar]", "  ∗ install dune                    2.7.1    [required by ssl]", "  ∗ install ocamlfind               1.8.1    [required by taglib, opus, liquidsoap, etc.]", "  ∗ install conf-libssl             2        [required by ssl]", "  ∗ install conf-libpcre            1        [required by pcre]", "  ∗ install uchar                   0.0.2    [required by sedlex]", "  ∗ install result                  1.5      [required by dune-configurator, ocaml-migrate-parsetree]", "  ∗ install ppx_derivers            1.2.1    [required by ocaml-migrate-parsetree]", "  ∗ install menhirSdk               20200624 [required by menhir]", "  ∗ install menhirLib               20200624 [required by menhir]", "  ∗ install dtools                  0.4.2    [required by liquidsoap]", "  ∗ install camomile                1.0.2    [required by liquidsoap]", "  ∗ install taglib                  0.3.3", "  ∗ install samplerate              0.1.4", "  ∗ install ogg                     0.5.2    [required by opus, flac, liquidsoap, vorbis]", "  ∗ install mad                     0.4.5", "  ∗ install lame                    0.3.3", "  ∗ install fdkaac                  0.3.1", "  ∗ install base-bytes              base     [required by faad]", "  ∗ install csexp                   1.3.1    [required by dune-configurator]", "  ∗ install ocaml-migrate-parsetree 1.7.3    [required by sedlex]", "  ∗ install menhir                  20200624 [required by liquidsoap]", "  ∗ install vorbis                  0.7.1", "  ∗ install opus                    0.1.3", "  ∗ install flac                    0.1.5", "  ∗ install mm                      0.5.0    [required by liquidsoap]", "  ∗ install faad                    0.4.0", "  ∗ install dune-configurator       2.7.1    [required by ssl]", "  ∗ install ppx_tools_versioned     5.4.0    [required by sedlex]", "  ∗ install ssl                     0.5.9", "  ∗ install pcre                    7.4.6    [required by duppy, liquidsoap]", "  ∗ install gen                     0.5.3    [required by sedlex]", "  ∗ install cry                     0.6.1", "  ∗ install duppy                   0.8.0", "  ∗ install sedlex                  2.2      [required by liquidsoap]", "  ∗ install liquidsoap              1.4.2", "===== ∗ 38 =====", "", "<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>", "[csexp.1.3.1] downloaded from cache at https://opam.ocaml.org/cache", "[cry.0.6.1] downloaded from cache at https://opam.ocaml.org/cache", "[dtools.0.4.2] downloaded from cache at https://opam.ocaml.org/cache", "[camomile.1.0.2] downloaded from cache at https://opam.ocaml.org/cache", "[dune.2.7.1] downloaded from cache at https://opam.ocaml.org/cache", "[dune-configurator.2.7.1] downloaded from cache at https://opam.ocaml.org/cache", "[duppy.0.8.0] downloaded from cache at https://opam.ocaml.org/cache", "[faad.0.4.0] downloaded from cache at https://opam.ocaml.org/cache", "[fdkaac.0.3.1] downloaded from cache at https://opam.ocaml.org/cache", "[gen.0.5.3] downloaded from cache at https://opam.ocaml.org/cache", "[flac.0.1.5] downloaded from cache at https://opam.ocaml.org/cache", "[lame.0.3.3] downloaded from cache at https://opam.ocaml.org/cache", "[mad.0.4.5] downloaded from cache at https://opam.ocaml.org/cache", "[liquidsoap.1.4.2] downloaded from cache at https://opam.ocaml.org/cache", "[menhir.20200624] downloaded from cache at https://opam.ocaml.org/cache", "[menhirSdk.20200624] found in cache", "[mm.0.5.0] downloaded from cache at https://opam.ocaml.org/cache", "[menhirLib.20200624] downloaded from cache at https://opam.ocaml.org/cache", "[ocaml-migrate-parsetree.1.7.3] downloaded from cache at https://opam.ocaml.org/cache", "[ocamlbuild.0.14.0] downloaded from cache at https://opam.ocaml.org/cache", "[ocamlfind.1.8.1] downloaded from cache at https://opam.ocaml.org/cache", "[ogg.0.5.2] downloaded from cache at https://opam.ocaml.org/cache", "[opus.0.1.3] downloaded from cache at https://opam.ocaml.org/cache", "[pcre.7.4.6] downloaded from cache at https://opam.ocaml.org/cache", "[ppx_derivers.1.2.1] downloaded from cache at https://opam.ocaml.org/cache", "[result.1.5] downloaded from cache at https://opam.ocaml.org/cache", "[ppx_tools_versioned.5.4.0] downloaded from cache at https://opam.ocaml.org/cache", "[samplerate.0.1.4] downloaded from cache at https://opam.ocaml.org/cache", "[ssl.0.5.9] downloaded from cache at https://opam.ocaml.org/cache", "[sedlex.2.2] downloaded from cache at https://opam.ocaml.org/cache", "[taglib.0.3.3] downloaded from cache at https://opam.ocaml.org/cache", "[uchar.0.0.2] downloaded from cache at https://opam.ocaml.org/cache", "[vorbis.0.7.1] downloaded from cache at https://opam.ocaml.org/cache", "", "<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>", "∗ installed conf-m4.1", "∗ installed conf-pkg-config.1.3", "∗ installed conf-libpcre.1", "∗ installed conf-libssl.2", "∗ installed ocamlfind.1.8.1"]}
```

**Comment by SlvrEagle23** [comment]
@NicoxDJ I am unable to reproduce the issues you're having with Liquidsoap on the Raspberry Pi.

Since we have done a fair amount of work already to ensure compatibility with ARM64 devices, I am closing this issue as the original reason for its creation has been resolved on our end.

**Comment by christiansacks** [comment]
I am getting the same issue on an x86_64 system running Ubuntu 18.04. I just pulled the latest version too, so ... problem still persists?

**Comment by NicoxDJ** [comment]
@christiansacks Actually these retries are normal. It's just the installer checking is the installation of Liquidsoap is finished, so to continue with the next things.
