### ISSUE TITLE
Statistic home page

### ISSUE THREAD

**Issue by radiobellissima** [AzuraCast/AzuraCast#3268]
![Test](https://user-images.githubusercontent.com/57127248/95751955-9ab7c400-0c9f-11eb-8d62-6e0ddd0e4da6.png)

Hi, after updating azura to the latest version available, the statistics in the home don't work anymore. How can I solve?

Thanks
Marcello

**Comment by SC2Mitch** [comment]
We're having the same issues

**Comment by ITC-Media** [comment]
Same here too

**Comment by radiobellissima** [comment]
I have now discovered that the stations are clickable, if you try to click on "all stations" the graph will adjust even if the measurement parameters seem different. I don't know if it is normal now to hear someone from development if it should work like this.
![Test](https://user-images.githubusercontent.com/57127248/95786287-88597c80-0cd7-11eb-944b-768319af6b21.png)

**Comment by SlvrEagle23** [comment]
@radiobellissima Should be fixed in the latest commit. Was just a minor query error on my part.

**Comment by radiobellissima** [comment]
This will then be corrected automatically or my manual action is required

**Comment by SlvrEagle23** [comment]
@radiobellissima You should update your AzuraCast installation to the latest version to receive the updated code.

**Comment by radiobellissima** [comment]
So I just have to wait for the next release Release my current is this #66861f3 (2020-10-11 3:10) • Docker • PHP 7.4.

**Comment by SlvrEagle23** [comment]
@radiobellissima No, I committed the fix directly to our "rolling release" channel, so if you update right now you'll get it.

**Comment by radiobellissima** [comment]
ok, thanks as soon as i can i update again. I wait for the fewest number of listeners so as not to drop them.

**Comment by YosefAdPro** [comment]
@SlvrEagle23 
My dashboard is still empty even after an update
 v0.10.4, #b31f892 (2020-10-13 4:50)

![image](https://user-images.githubusercontent.com/11810187/95821077-f16dde00-0d31-11eb-96de-b7f707d6bad4.png)

**Comment by radiobellissima** [comment]
I have updated to the latest version available. Now the problem has changed but it still exists everything is marked much less almost zero.
![Test](https://user-images.githubusercontent.com/57127248/96332496-8e978200-1064-11eb-8d16-c93e764e18db.png)

**Comment by SlvrEagle23** [comment]
@radiobellissima Should be fixed as of the latest update.

**Comment by radiobellissima** [comment]
![Test](https://user-images.githubusercontent.com/57127248/96354652-3cdd0f00-10d9-11eb-92b6-559c152eed4e.png)
Work fine now :-)
