### ISSUE TITLE
error mysql new update azuracast

### ISSUE THREAD

**Issue by fast97** [AzuraCast/AzuraCast#3460]
Hello, need help. While doing the new update I get this error message mysql see my screenshot.
System centos8.
Thanks
![cap140](https://user-images.githubusercontent.com/51033222/100187883-5730b680-2ee9-11eb-969b-87901dffd797.png)

**Comment by vitoyucepi** [comment]
Introduced by #3347.

**Comment by SlvrEagle23** [comment]
@fast97 @vitoyucepi If you update to the latest rolling-release version this issue should be fixed.

**Comment by vitoyucepi** [comment]
@SlvrEagle23 not working.
In my case artist is `NULL`.

**Comment by reans** [comment]
just update a seconds ago but same error..

![image](https://user-images.githubusercontent.com/27730047/100204704-24b1a880-2f3f-11eb-9abf-a26c60aed5df.png)

**Comment by reans** [comment]
mine too... just update seconds ago but same error..

![image](https://user-images.githubusercontent.com/27730047/100204795-4743c180-2f3f-11eb-8d1b-c7e1e718c1ca.png)

**Comment by fast97** [comment]
My update version is : Propulsé par AzuraCast • Rolling Release #43236b6 (2020-11-25 8:19) • Docker • PHP 7.4
and nothing has changed the problem is still there.

**Comment by vitoyucepi** [comment]
should be like `WHERE artist != \'\' OR title != \'\' OR artist IS NOT NULL OR title IS NOT NULL`

**Comment by SlvrEagle23** [comment]
Let me know if the latest update fixes this.

**Comment by vitoyucepi** [comment]
@SlvrEagle23 logic bug.
`WHERE artist IS NOT NULL AND title IS NOT NULL`

**Comment by fast97** [comment]
for me no : Rolling Release #90bb109 (2020-11-25 9:06)

**Comment by SlvrEagle23** [comment]
One more attempt! Thanks for the quick responses folks.

**Comment by vitoyucepi** [comment]
Solved for me.

**Comment by vitoyucepi** [comment]
@SlvrEagle23 what will happen if `artist` and `title` will be empty string at the same time in more then one track?

**Comment by SlvrEagle23** [comment]
@vitoyucepi Really any media file with both an empty artist and title is probably a media file that failed to process correctly, and that we shouldn't have created a record for. Things like album art files, etc.

It won't create any issue that multiple of those media records have the same song hash, since those songs shouldn't be cued up and played anyway.

**Comment by fast97** [comment]
I still have the problem the updates are not done and the error on the screenshot is the same.
Thank you

**Comment by SlvrEagle23** [comment]
@fast97 It's the exact same? It definitely shouldn't be, given the recent updates.

**Comment by vitoyucepi** [comment]
Maybe some sort of cache. I've notice that too.
To upgrade I've run the update script twice.

For the first time I've received `OR` error.
At that moment, image might not have been updated in the registry. So I rerun script.
For the second run everything was ok.

**Comment by fast97** [comment]
/var/azuracast# ./docker.sh update
Please make sure your AzuraCast installation is backed up before updating. Continue? [Y/n] y
Pulling mariadb                 ... done
Pulling redis                   ... done
Pulling stations                ... done
Pulling web                     ... done
Pulling nginx_proxy             ... done
Pulling nginx_proxy_letsencrypt ... done
Stopping azuracast_nginx_proxy_letsencrypt_1 ... done
Stopping azuracast_nginx_proxy_1             ... done
Stopping azuracast_web                       ... done
Stopping azuracast_stations                  ... done
Stopping azuracast_redis_1                   ... done
Stopping azuracast_mariadb_1                 ... done
Removing azuracast_nginx_proxy_letsencrypt_1 ... done
Removing azuracast_nginx_proxy_1             ... done
Removing azuracast_web                       ... done
Removing azuracast_stations                  ... done
Removing azuracast_redis_1                   ... done
Removing azuracast_mariadb_1                 ... done
Removing network azuracast_backend
Removing network azuracast_frontend
azuracast_www_vendor
azuracast_tmp_data
azuracast_redis_data
Creating network "azuracast_backend" with driver "bridge"
Creating network "azuracast_frontend" with driver "bridge"
Creating volume "azuracast_www_vendor" with default driver
Creating volume "azuracast_tmp_data" with default driver
Creating volume "azuracast_redis_data" with default driver
Creating azuracast_redis_1   ... done
Creating azuracast_mariadb_1 ... done
Creating azuracast_stations  ... done
Starting up AzuraCast services...
Services started up and ready!
AzuraCast Setup
(Environment: production)

AzuraCast Setup
===============

Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...
 * Environment: Production
 * Installation Method: Docker

 ! [NOTE] Running in update mode.                                               


Running Database Migrations
---------------------------


                                                                                
 [WARNING] You have 1 previously executed migrations in the database that are   
           not registered migrations

**Comment by fast97** [comment]
is this update script executed? ./docker.sh update

**Comment by vitoyucepi** [comment]
```
Services started up and ready!
AzuraCast Setup
(Environment: production)
AzuraCast Setup
===============
Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...
 * Environment: Production
 * Installation Method: Docker
 ! [NOTE] Running in update mode.                                               
Running Database Migrations
---------------------------
[notice] Migrating up to App\Entity\Migration\Version20201125023226
[notice] finished in 50.7ms, used 24M memory, 1 migrations executed, 1 sql queries
Generating Database Proxy Classes
---------------------------------
 Processing entity "App\Entity\Settings"
 Processing entity "App\Entity\StorageLocation"
 Processing entity "App\Entity\StationMedia"
 Processing entity "App\Entity\CustomField"
 Processing entity "App\Entity\StationPlaylistMedia"
 Processing entity "App\Entity\StationPlaylist"
 Processing entity "App\Entity\StationMediaCustomField"
 Processing entity "App\Entity\Station"
 Processing entity "App\Entity\SongHistory"
 Processing entity "App\Entity\StationStreamer"
 Processing entity "App\Entity\RolePermission"
 Processing entity "App\Entity\StationMount"
 Processing entity "App\Entity\StationRemote"
 Processing entity "App\Entity\StationWebhook"
 Processing entity "App\Entity\SftpUser"
 Processing entity "App\Entity\StationStreamerBroadcast"
 Processing entity "App\Entity\Relay"
 Processing entity "App\Entity\User"
 Processing entity "App\Entity\StationRequest"
 Processing entity "App\Entity\AuditLog"
 Processing entity "App\Entity\Listener"
 Processing entity "App\Entity\Analytics"
 Processing entity "App\Entity\Role"
 Processing entity "App\Entity\StationQueue"
 Processing entity "App\Entity\StationPlaylistFolder"
 Processing entity "App\Entity\ApiKey"
 Processing entity "App\Entity\StationSchedule"
 Proxy classes generated to "/var/azuracast/www_tmp/proxies"
Reload System Data
------------------
 [OK] Local cache flushed.                                                      
 [OK] Message queue cleared.                                                    
Refreshing All Stations
-----------------------
Restarting all radio stations...
--------------------------------
 0/1 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
 [OK] AzuraCast is now updated to the latest version!    
```

**Comment by fast97** [comment]
root@plesk:/var/azuracast# ./docker.sh update
Please make sure your AzuraCast installation is backed up before updating. Continue? [Y/n] y
Pulling mariadb                 ... done
Pulling redis                   ... done
Pulling stations                ... done
Pulling web                     ... done
Pulling nginx_proxy             ... done
Pulling nginx_proxy_letsencrypt ... done
Stopping azuracast_nginx_proxy_letsencrypt_1 ... done
Stopping azuracast_nginx_proxy_1             ... done
Stopping azuracast_web                       ... done
Stopping azuracast_stations                  ... done
Stopping azuracast_mariadb_1                 ... done
Stopping azuracast_redis_1                   ... done
Removing azuracast_nginx_proxy_letsencrypt_1 ... done
Removing azuracast_nginx_proxy_1             ... done
Removing azuracast_web                       ... done
Removing azuracast_stations                  ... done
Removing azuracast_mariadb_1                 ... done
Removing azuracast_redis_1                   ... done
Removing network azuracast_backend
Removing network azuracast_frontend
azuracast_www_vendor
azuracast_tmp_data
azuracast_redis_data
Creating network "azuracast_backend" with driver "bridge"
Creating network "azuracast_frontend" with driver "bridge"
Creating volume "azuracast_www_vendor" with default driver
Creating volume "azuracast_tmp_data" with default driver
Creating volume "azuracast_redis_data" with default driver
Creating azuracast_stations  ... done
Creating azuracast_redis_1   ... done
Creating azuracast_mariadb_1 ... done
Starting up AzuraCast services...
Services started up and ready!
AzuraCast Setup
(Environment: production)

AzuraCast Setup
===============

Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...
 * Environment: Production
 * Installation Method: Docker

 ! [NOTE] Running in update mode.                                               


Running Database Migrations
---------------------------


                                                                                
 [WARNING] You have 1 previously executed migrations in the database that are   
           not registered migrations.                                           
                                                                                

 >> 2020-09-11 14:45:04 (20161003041904)

**Comment by fast97** [comment]
mysql blocks I think. Will I have to install azuracast again?

**Comment by torontocast** [comment]
Same issue here..  not able to update and receiving the same errors.

**Comment by SlvrEagle23** [comment]
Latest update should resolve this issue. Note that this latest migration is more of a "cleanup" operation, and doesn't really make fundamental changes to the database, so if it fails you can just run it again without issue.

**Comment by fast97** [comment]
yes yes good  all is working again thank you thank you thank you
