### ISSUE TITLE
M3U and PLS file association as audio file instead of html file

### ISSUE THREAD

**Issue by amavarick** [AzuraCast/AzuraCast#355]
When I'm on the Icecast page, left clicking on the M3U link will automatically recognize the file type as an mp3 audio stream and offer to open my media player.

![image](https://user-images.githubusercontent.com/20918832/34316851-9935fe9e-e76d-11e7-805b-6ad8795925d1.png)

Mousing over the m3u link on the Icecast page shows the following URL:
![image](https://user-images.githubusercontent.com/20918832/34316933-65e55398-e770-11e7-8448-5559cdc5f1a4.png)

However when clicking on m3u link on the public/music page the file type is html instead of mp3 and does not offer a music player option but offers html editors.

![image](https://user-images.githubusercontent.com/20918832/34316870-751ed14c-e76e-11e7-802b-8f6ef5dd6529.png)

Mousing over the m3u link on the AzuraCast public radio page shows the following URL:
![image](https://user-images.githubusercontent.com/20918832/34316941-abb773e2-e770-11e7-8d5f-eba6f5217cd7.png)

I'm assuming because the AzuraCast URL doesn't have a file extension, its assumed to be html file type then downloads instead of offers to play like the Icecast page?

On a desktop, the easy workaround is to download the pls or m3u file and then open it and it will open in the default music app properly.  My main concern is with smart phones (Android) where even with Chrome, it doesn't know how to handle the pls and m3u extension using the AzuraCast Public page but if I click on the m3u from Icecast page, it tries to open the music player properly.  Some of my radio listeners on mobile devices would not be tech savvy enough to know to download the m3u or pls file and open it.

As always, thank you so much for your time.  This is a beautiful software package and I'm glad you recommended docker.

**Comment by SlvrEagle23** [comment]
@amavarick Should be fixed now. The playlist download page wasn't using the newer PSR-7 HTTP response format, and thus the content headers weren't setting correctly.

**Comment by amavarick** [comment]
Looks like they're properly typed now, thank you!  See screenshots.  However, Android doesn't know how to handle these two files rather than just download them.  Please see additional details below the 2 validation shots.

![image](https://user-images.githubusercontent.com/20918832/34358064-4a4acd1e-ea1a-11e7-870a-836e6b45edcd.png)

![image](https://user-images.githubusercontent.com/20918832/34358070-66d8fba4-ea1a-11e7-8fd5-ed45c3952cb0.png)

This is the behavior when on the Icecast page clicking on the m3u link:
![image](https://user-images.githubusercontent.com/20918832/34358186-6639568e-ea1b-11e7-9a05-c5770292a182.png)

This is the behavior when on the Azuracast public radio page clicking on the m3u link:
![image](https://user-images.githubusercontent.com/20918832/34358199-a5a7a9ba-ea1b-11e7-8c00-582e9defbef4.png)

I have other sites where I create a pls and m3u file and android will ask to open them in an audio player.  On Azuracast public radio page, it asks only to download.  If I download the pls or m3u on my Android, it will say sorry failed to play file.

**Specifically the desired behavior**:
1.  On Android, in the public radio page, clicking on m3u or pls link should offer to play using an audio app as shown in a screenshots above rather than only to download the file.  Please use the icecast page as an example.  Maybe adding the file extension in the download will trigger it?  I notice on the public radio the download url is just /m3u rather than the file name.  Whereas on the icecast page the file extension is .mp3.m3u

2.  On Android, downloaded m3u and pls files from the public radio page don't play.  It says "sorry, failed to play the file"  However, I can create m3u and pls files and have my same Android phone to open a player with them.

Please let me know if I should create a new ticket for this.  I "thought" changing the browser association would fix the opening of the file.  As always, thank you so much for your time.

**Comment by SlvrEagle23** [comment]
@amavarick This one really puts us web dev folk in a pickle. The difference between Icecast/Shoutcast and AzuraCast in this case is that AzuraCast sends the "Content-Disposition: attachment" header, which is the only way to specify a manual downloadable filename to browsers. Sadly, it also confuses mobile browsers into treating the file like something that should strictly be downloaded only, which prevents the "Open with" dialog from popping up.

For the sake of usability, I'm erring on the side of matching Icecast/Shoutcast's behavior, removing the "Content-Disposition" header, and making things work more smoothly on mobile. The downside is that desktop browsers will be prompted with a download whose filename is just "pls" or "m3u", instead of "station_name.pls".

I could get into the business of detecting whether a user is mobile or not and changing the header accordingly, but that would dramatically overcomplicate what is otherwise a simple feature.

**Comment by amavarick** [comment]
On my android Chrome, I deleted all cache and closed browser and reopened.  Went to public radio page and tried both the pls and m3u links.

PLS asked to download just like before.
M3U Different behavior as didn't ask to download but rather than asking what program (like icecast m3u link) to open the file with, it opened a player inside of Chrome and wouldn't play.  Clicking on the triangle to play accepts but no time increment and no sound with audio up.

I tried both with http and https.
The contents of the m3u files are respectively:
http://stream1.domain.tld:8000/radio.mp3?1514333300
https://stream1.domain.tld/radio/8000/radio.mp3?1514333368

**Comment by amavarick** [comment]
Just for posterity, retested the above with Adblock disabled.  Unfortunately that did not resolve this particular issue.

**Comment by SlvrEagle23** [comment]
@amavarick You'll notice that Icecast doesn't offer a PLS download, but rather just an M3U. There's no assurance that just because one of those formats works, that the other will, which is exactly why AzuraCast includes both so users can find which works better for them.

Since I'm sending the proper MIME type for both playlist formats, matching the playlist export functionality of Icecast for M3U and Shoutcast for PLS, I'm closing this issue as resolved.
