### ISSUE TITLE
Trying to delete/update Streamers/DJ accounts but no outcome, no error occurs and docker is also updated..

### ISSUE THREAD

**Issue by Ha1DeR-GH** [AzuraCast/AzuraCast#3590]
**Using Docker installation method**

**AzuraCast version**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@Ha1DeR-GH Please actually fill in the issue template when reporting a new issue.

Based on your issue title, I believe you're referring to an issue that was fixed as of a few rolling release updates ago. You may need to update your installation to fix this issue.

**Comment by Ha1DeR-GH** [comment]
> @Ha1DeR-GH Please actually fill in the issue template when reporting a new issue.
> 
> Based on your issue title, I believe you're referring to an issue that was fixed as of a few rolling release updates ago. You may need to update your installation to fix this issue.

How do I update installation ? Updating installation would delete the station data respectively.?

**Comment by SlvrEagle23** [comment]
@Ha1DeR-GH Follow the instructions here to update your installation: https://www.azuracast.com/administration/system/updating.html#updating-azuracast

It should not delete your station data or any other settings during the update process, but it's recommended to take a backup of your system before updating just in case.

**Comment by Ha1DeR-GH** [comment]
> @Ha1DeR-GH Follow the instructions here to update your installation: https://www.azuracast.com/administration/system/updating.html#updating-azuracast
> 
> It should not delete your station data or any other settings during the update process, but it's recommended to take a backup of your system before updating just in case.

I've already did that, and I'm still not able to delete/update streamer/DJ account data.

**Comment by SlvrEagle23** [comment]
@Ha1DeR-GH Then please submit a proper GitHub issue with as much information as you can provide, complete the template we give you, and give us any screenshots or logs that you have.
