### ISSUE TITLE
AlbumArt for streaming stations

### ISSUE THREAD

**Issue by killertez** [AzuraCast/AzuraCast#3652]
my stations isn't coming up with the songs album art auto is there a way to fix this issue 
http://vpn.auscfhost.com/public/aussies_bar_radio

**Using Docker installation method**

**AzuraCast version**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by jdrodriguez** [comment]
I am having the same issue after I updated the station to the latest version of AC. Anyone can help with this?

**Comment by SlvrEagle23** [comment]
@killertez @jdrodriguez I understand there's possibly an error happening here, but we're not getting nearly enough information to be able to diagnose and debug this issue. There's a reason we have the issue template we do, as it provides us with much of that needed information, so please complete that template when creating issues instead of just ignoring or removing it.

Namely, we need:
 - Where is this issue happening (only on public pages, or on the profile, public pages, media manager, etc.)
 - If you upload media, do you see album art for that media next to it? Do you see any album art on the media manager?
 - Is it just for specific tracks or are all tracks showing the default album art?

**Comment by SlvrEagle23** [comment]
This may have also been caused by an update that was released this morning and has since been fixed, which would've also impacted the ability of the Liquidsoap AutoDJ to send "feedback" for the upcoming track back to AzuraCast, which is sometimes what we depend on when adding rich metadata (like album art and playback times) to media. This has been fixed as of the latest rolling-release version, so I would advise updating to see if that fixes things first.

**Comment by killertez** [comment]
> This may have also been caused by an update that was released this morning and has since been fixed, which would've also impacted the ability of the Liquidsoap AutoDJ to send "feedback" for the upcoming track back to AzuraCast, which is sometimes what we depend on when adding rich metadata (like album art and playback times) to media. This has been fixed as of the latest rolling-release version, so I would advise updating to see if that fixes things first.
--------------------------------------------------------------------------------------------------------------------------------------------
root@vps283222:~# cd /var/azuracast
root@vps283222:/var/azuracast# ./docker.sh update
Please make sure your AzuraCast installation is backed up before updating. Conti                                                                    nue? [Y/n] y
Pulling mariadb                 ... done
Pulling redis                   ... done
Pulling stations                ... done
Pulling web                     ... done
Pulling nginx_proxy             ... done
Pulling nginx_proxy_letsencrypt ... done
Stopping azuracast_nginx_proxy_letsencrypt_1 ... done
Stopping azuracast_nginx_proxy_1             ... done
Stopping azuracast_web                       ... done
Stopping azuracast_stations                  ... done
Stopping azuracast_mariadb_1                 ... done
Stopping azuracast_redis_1                   ... done
Removing azuracast_nginx_proxy_letsencrypt_1 ... done
Removing azuracast_nginx_proxy_1             ... done
Removing azuracast_web                       ... done
Removing azuracast_stations                  ... done
Removing azuracast_mariadb_1                 ... done
Removing azuracast_redis_1                   ... done
Removing network azuracast_backend
Removing network azuracast_frontend
azuracast_www_vendor
azuracast_tmp_data
azuracast_redis_data
Creating network "azuracast_backend" with driver "bridge"
Creating network "azuracast_frontend" with driver "bridge"
Creating volume "azuracast_www_vendor" with default driver
Creating volume "azuracast_tmp_data" with default driver
Creating volume "azuracast_redis_data" with default driver
Creating azuracast_stations  ... done
Creating azuracast_mariadb_1 ... done
Creating azuracast_redis_1   ... done
Starting up AzuraCast services...
Services started up and ready!
AzuraCast Setup
(Environment: production)

AzuraCast Setup
===============

Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are s                                                                    et up...
 * Environment: Production
 * Installation Method: Docker

 ! [NOTE] Running in update mode.


Running Database Migrations
---------------------------



 [OK] Already at the latest version
      ("App\Entity\Migration\Version20201211164613")



Generating Database Proxy Classes
---------------------------------


 Processing entity "App\Entity\SettingsTable"
 Processing entity "App\Entity\StorageLocation"
 Processing entity "App\Entity\StationMedia"
 Processing entity "App\Entity\CustomField"
 Processing entity "App\Entity\StationQueue"
 Processing entity "App\Entity\Station"
 Processing entity "App\Entity\StationPlaylist"
 Processing entity "App\Entity\StationRequest"
 Processing entity "App\Entity\StationPlaylistMedia"
 Processing entity "App\Entity\StationMediaCustomField"
 Processing entity "App\Entity\SongHistory"
 Processing entity "App\Entity\StationStreamer"
 Processing entity "App\Entity\RolePermission"
 Processing entity "App\Entity\StationMount"
 Processing entity "App\Entity\StationRemote"
 Processing entity "App\Entity\StationWebhook"
 Processing entity "App\Entity\SftpUser"
 Processing entity "App\Entity\StationSchedule"
 Processing entity "App\Entity\StationPlaylistFolder"
 Processing entity "App\Entity\StationStreamerBroadcast"
 Processing entity "App\Entity\User"
 Processing entity "App\Entity\Listener"
 Processing entity "App\Entity\MessengerMessage"
 Processing entity "App\Entity\ApiKey"
 Processing entity "App\Entity\AuditLog"
 Processing entity "App\Entity\Analytics"
 Processing entity "App\Entity\Role"
 Processing entity "App\Entity\Relay"

 Proxy classes generated to "/var/azuracast/www_tmp/proxies"

Reload System Data
------------------



 [OK] Local cache flushed.




 [OK] All message queues cleared.



Refreshing All Stations
-----------------------


Restarting all radio stations...
--------------------------------

 15/15 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%



 [OK] AzuraCast is now updated to the latest version!


azuracast_stations is up-to-date
azuracast_redis_1 is up-to-date
azuracast_mariadb_1 is up-to-date
Creating azuracast_web ... done
Creating azuracast_nginx_proxy_1 ... done
Creating azuracast_nginx_proxy_letsencrypt_1 ... done
Clean up all stopped Docker containers and images to save space? [Y/n] y
Deleted Images:
untagged: alpine@sha256:39eda93d15866957feaee28f8fc5adb545276a64147445c64992ef69                                                                    804dbf01
deleted: sha256:f70734b6a266dcb5f44c383274821207885b549b75c8e119404917a61335981a

Total reclaimed space: 0B
Update complete!
root@vps283222:/var/azuracast#

i have done an update but still hasn't fixed the album art.

**Comment by ANSASERVERS** [comment]
Possibly this is the root cause. We have the same issue:

DevTools failed to load SourceMap: Could not load content for https://vpn.auscfhost.com/static/dist/lib/bootstrap/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://vpn.auscfhost.com/static/dist/lib/bootstrap-vue/bootstrap-vue.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://vpn.auscfhost.com/static/dist/lib/moment/moment.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://vpn.auscfhost.com/static/dist/lib/moment/locales.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://vpn.auscfhost.com/static/dist/lib/bootstrap-vue/bootstrap-vue.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

There is css files missing on the public page. We are running an older release installed about 2 weeks ago.

In Chrome, hit F12 and ten go to Console.

**Comment by jdrodriguez** [comment]
I ran the latest update and it fixed the issue.

**Comment by jdrodriguez** [comment]
Hello again... The latest update fixed it but not 100%. Some tracks, that have an image assigned, are still not showing the album art. Is there a minimum size required for the image? The only difference I am noticing between a few tracks I looked at that are showing the art and those that are not is that the image size for the ones that are not is small, 400x400.

**Comment by killertez** [comment]
> Hello again... The latest update fixed it but not 100%. Some tracks, that have an image assigned, are still not showing the album art. Is there a minimum size required for the image? The only difference I am noticing between a few tracks I looked at that are showing the art and those that are not is that the image size for the ones that are not is small, 400x400.

yeah but  playing the songs from the website or do you have a studio playing the stream to the azuracast

**Comment by jdrodriguez** [comment]
It is playing directly on the website using the autodj

**Comment by killertez** [comment]
im using radioboss to stream to the website... .album art works fine on Tunein...    but not showing up on azuracast

**Comment by Vaalyn** [comment]
@killertez to clarify, you are streaming with RadioBoss via the `DJ Accounts` feature or directly to IceCast and want the album art from your local songs to show up when streaming with this software, right?

AzuraCast does not try to pull album artworks from live streams and there are currently no plans to add this. (You are free to create a feature request for it on https://features.azuracast.com/ though).

**Comment by Vaalyn** [comment]
@jdrodriguez I've tested songs with album art that is 256x256px and they show up without an issue (tested with artwork 
added to the file before upload and added through AzuraCast after upload). I general there is no specific restriction to the album art size so I think this is probably not the source of the issue on your files.

If you can provide me with 1 of those files were the art is not showing up for you I can test it on my test installation.

**Comment by ANSASERVERS** [comment]
Why Can you not add last.fm API which will use the artist and song details to pull the details needed. Pointless having a public player that does not support Album art. If you can not support this, you should have an option to turn off the album art all together.

As a stream hoster and a station owner, running a station via autoDJ from a server without proper automation is just pointless.

**Comment by ANSASERVERS** [comment]
Here is my web player that i built using PHP / HTML and api.last.fm. The issue is it works hit and miss because i have not got https on the web stream

http://player.phazern.com.au/web/

**Comment by Vaalyn** [comment]
> Why Can you not add last.fm API which will use the artist and song details to pull the details needed.

See this issue about this topic: https://github.com/AzuraCast/AzuraCast/issues/102

> Pointless having a public player that does not support Album art.

The public player DOES support album art as well as the AutoDJ. Most streaming software that is used to stream from your own PC does not support sending album art. For example Mixxx, Butt, VirtualDJ (just to name a few) so that has not been a priority for us.

> you should have an option to turn off the album art all together.

**Comment by SlvrEagle23** [comment]
Support for external album art retrieval has been added in the latest stable release.
