### ISSUE TITLE
SoundExchange Report - ISRC is blank (empty) when exporting the text file

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#3963]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #5bcfeb7 (2021-04-01 0:18) • Docker • PHP 7.4

**Host Operating System**
Ubuntu 18.04.5 | MacOS Catalina 10.15.7

**Describe the bug**
When exporting the report from Report >> SoundExchange Royalties >> Generate report, the text file's ISRC column is empty. Not showing the metadata even if there is an ISRC data on the song file.

**To Reproduce**
1. Go to Report >> SoundExchange Royalties
2. Click on Generate report
3. Open the report 
4. ISRC column is empty ^^

**Expected behavior**
ISRC column for each song file should generate what is added on the song file's ISRC field

**Screenshots**
https://share.getcloudapp.com/llu5zq82

**Device(s):**
- Device: Macbook air 2020
- OS: MacOS Catalina 10.15.7
- Browser: Chrome and Safari

Thank you!

**Comment by SlvrEagle23** [comment]
@ErnestPH Found the error; should be fixed as of the latest Rolling Release update.

**Comment by ErnestPH** [comment]
@SlvrEagle23 When I updated it and click generate report - got an error 500 

> [Semantical Error] line 0, col 105 near 'station_id =': Error: Class App\Entity\StationMedia has no field or association named station_id
QueryException.php : 63

**Comment by SlvrEagle23** [comment]
@ErnestPH I've looked into the report and not only fixed the errors with the queries but also added the ISRC auto-fetching back (though this time it's using the open MusicBrainz database).

**Comment by ErnestPH** [comment]
Thanks @SlvrEagle23 but unfortunately still not working... Got an 500 error for range March 1 - 31
`[Semantical Error] line 0, col 105 near 'station = :s': Error: Class App\Entity\StationMedia has no field or association named station
QueryException.php : 63`

When date range is reduced to March 1 to a few days it keeps on loading then goes to error 500

Thanks!

**Comment by ErnestPH** [comment]
Just updated to  #168327f (2021-04-06 1:02) • Docker • PHP 7.4 but still got the 500 error. Fyi @SlvrEagle23 Thanks!
<img width="698" alt="Screen Shot 2021-04-06 at 2 47 57 PM" src="https://user-images.githubusercontent.com/43772409/113670158-53a70a80-96e7-11eb-89ef-9ef8928bbf7b.png">

**Comment by SlvrEagle23** [comment]
@ErnestPH Should be fixed now.

**Comment by ErnestPH** [comment]
Unfortunately, it didn't... Although there's no error 500 but it just keeps loading and got the Cloudflare error 524 (timeout).
Even only tried Exporting March 1 - March 1...

@SlvrEagle23

**Comment by SlvrEagle23** [comment]
@ErnestPH You may have updated a little too quickly there, as the fix was still deploying.

There's a built-in automatic ISRC retrieval that may be causing trouble.

**Comment by ErnestPH** [comment]
I see. Thank you. I will just wait for it. Currently on Rolling Release #dbd3add

**Comment by ErnestPH** [comment]
I can confirm that it's working fine if you have few songs... I guess the work around here is not to add it in Cloudflare as it only has few seconds for the timeout error... Or maybe there's another solution so it won't check all the songs? Thanks!

**Comment by SlvrEagle23** [comment]
@ErnestPH I made the ISRC fetching an optional thing; if you turn it off, it should fetch almost immediately.

**Comment by ErnestPH** [comment]
Awesome! It's working now. Thanks!
