### ISSUE TITLE
Station doesnt connect to LautFM Station and goes Offline after some time.

### ISSUE THREAD

**Issue by ReavMC** [AzuraCast/AzuraCast#4440]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.13.0

### What happened?

Hi!

I have installed Azuracast 0.13.0 over the docker installer.
Last time i installed it i had the Version 0.12.4 and all worked fine.

Now i have the Problem that my Azuracast Station not with my LautFM Station over Remote Relay.
My Stream doesent connect to LautFM and after some Time it goes offline.

Now i have looked in the Error log and found an error:

What can that be or can i install an older version of Azuracast?

### Relevant log output

```shell
[2021-08-01 18:32:00] WARN connection/get_ssl_certificate Invalid private key file /etc/nginx/certs/default.key (system lib)
[2021-08-01 18:32:00] WARN slave/slave_startup process has 65536 max file descriptor limit
[2021-08-01 18:36:14] WARN connection/get_ssl_certificate Invalid private key file /etc/nginx/certs/default.key (system lib)
[2021-08-01 18:36:14] WARN slave/slave_startup process has 65536 max file descriptor limit
[2021-08-01 18:39:24] WARN connection/get_ssl_certificate Invalid private key file /etc/nginx/certs/default.key (system lib)
[2021-08-01 18:39:24] WARN slave/slave_startup process has 65536 max file descriptor limit
```

**Comment by Vaalyn** [comment]
Please post your Liquidsoap Logs too.

**Comment by ReavMC** [comment]
`
2021/08/03 17:16:52 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:16:53 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:16:53 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:16:53 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:16:54 [clock.wallclock_main:2] We must catchup 45.50 seconds!
2021/08/03 17:16:54 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:16:54 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:16:54 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:16:55 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:16:55 [clock.wallclock_main:2] We must catchup 46.59 seconds!
2021/08/03 17:16:55 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:16:55 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:16:56 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:16:56 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:16:56 [clock.wallclock_main:2] We must catchup 47.75 seconds!
2021/08/03 17:16:56 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:16:56 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:16:57 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:16:57 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:16:58 [clock.wallclock_main:2] We must catchup 48.87 seconds!
2021/08/03 17:16:58 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:16:58 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:16:58 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:16:58 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:16:59 [clock.wallclock_main:2] We must catchup 50.04 seconds!
2021/08/03 17:16:59 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:16:59 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:00 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:00 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:00 [clock.wallclock_main:2] We must catchup 51.18 seconds!
2021/08/03 17:17:00 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:00 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:01 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:01 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:02 [clock.wallclock_main:2] We must catchup 52.40 seconds!
2021/08/03 17:17:02 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:02 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:02 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:02 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:03 [clock.wallclock_main:2] We must catchup 53.45 seconds!
2021/08/03 17:17:03 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:03 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:04 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:04 [clock.wallclock_main:2] We must catchup 54.35 seconds!
2021/08/03 17:17:04 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:04 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:05 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:05 [clock.wallclock_main:2] We must catchup 55.63 seconds!
2021/08/03 17:17:05 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:05 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:06 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:06 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:07 [clock.wallclock_main:2] We must catchup 56.86 seconds!
2021/08/03 17:17:07 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:07 [request:2] There are currently 147200 RIDs, possible request leak! Please check that you don't have a loop on empty/unavailable requests, or creating requests without destroying them. Decreasing request.grace_time can also help.
2021/08/03 17:17:07 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:07 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:08 [clock.wallclock_main:2] We must catchup 57.75 seconds!
2021/08/03 17:17:08 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:08 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:08 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:09 [clock.wallclock_main:2] We must catchup 58.69 seconds!
2021/08/03 17:17:09 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:09 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:09 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:10 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:10 [clock.wallclock_main:2] We must catchup 59.76 seconds!
2021/08/03 17:17:10 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:10 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:11 [clock.wallclock_main:2] Too much latency! Resetting active sources...
2021/08/03 17:17:11 [local_1:3] Closing connection...
2021/08/03 17:17:11 [local_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/08/03 17:17:11 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:11 [local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
strange error flushing buffer ... 
2021/08/03 17:17:11 [local_1:3] Will try again in 3.00 sec.
2021/08/03 17:17:11 [relay_1:3] Closing connection...
2021/08/03 17:17:11 [relay_1:3] Connecting mount /reavfm for source@stationsname.stream.laut.fm...
2021/08/03 17:17:11 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:11 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:12 [relay_1:3] Connection setup was successful.
2021/08/03 17:17:12 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:12 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:12 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:13 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:13 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:13 [clock.wallclock_main:2] We must catchup 1.37 seconds!
2021/08/03 17:17:13 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:13 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:14 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:14 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:15 [clock.wallclock_main:2] We must catchup 2.49 seconds!
2021/08/03 17:17:15 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:15 [local_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/08/03 17:17:15 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:15 [local_1:3] Connection setup was successful.
2021/08/03 17:17:15 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:16 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:16 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:16 [clock.wallclock_main:2] We must catchup 3.73 seconds!
2021/08/03 17:17:16 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:17 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:17 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:17 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:17 [clock.wallclock_main:2] We must catchup 4.90 seconds!
2021/08/03 17:17:17 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:18 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:18 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:18 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:18 [clock.wallclock_main:2] We must catchup 5.94 seconds!
2021/08/03 17:17:19 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:19 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:19 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:20 [clock.wallclock_main:2] We must catchup 7.03 seconds!
2021/08/03 17:17:20 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:20 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:20 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:21 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:21 [clock.wallclock_main:2] We must catchup 8.10 seconds!
2021/08/03 17:17:21 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:21 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:22 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:22 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:22 [clock.wallclock_main:2] We must catchup 9.28 seconds!
2021/08/03 17:17:22 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:23 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:23 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:23 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:24 [clock.wallclock_main:2] We must catchup 10.44 seconds!
2021/08/03 17:17:24 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:24 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:24 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:25 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:25 [clock.wallclock_main:2] We must catchup 11.60 seconds!
2021/08/03 17:17:25 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:25 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:26 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:26 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:26 [clock.wallclock_main:2] We must catchup 12.83 seconds!
2021/08/03 17:17:26 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:27 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:27 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:27 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:28 [clock.wallclock_main:2] We must catchup 13.96 seconds!
2021/08/03 17:17:28 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:28 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:28 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:29 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:29 [clock.wallclock_main:2] We must catchup 15.12 seconds!
2021/08/03 17:17:29 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:29 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:30 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:30 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:30 [clock.wallclock_main:2] We must catchup 16.28 seconds!
2021/08/03 17:17:30 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:31 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:31 [playlist_werbung:3] Loading playlist...
2021/08/03 17:17:31 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:31 [clock.wallclock_main:2] We must catchup 17.18 seconds!
2021/08/03 17:17:31 [playlist_werbung:3] No mime type specified, trying autodetection.
2021/08/03 17:17:31 [playlist_werbung:3] Playlist treated as format application/x-mpegURL
2021/08/03 17:17:32 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/start_ad_break.mp3".
2021/08/03 17:17:32 [playlist_werbung:3] Successfully loaded a playlist of 1 tracks.
2021/08/03 17:17:32 [playlist_default:3] Loading playlist...
2021/08/03 17:17:32 [playlist_default:3] No mime type specified, trying autodetection.
2021/08/03 17:17:32 [playlist_default:3] Playlist treated as format application/x-mpegURL
2021/08/03 17:17:32 [playlist_default:3] Successfully loaded a playlist of 0 tracks.
2021/08/03 17:17:32 [playlist_mainstream:3] Loading playlist...
2021/08/03 17:17:32 [playlist_mainstream:3] No mime type specified, trying autodetection.
2021/08/03 17:17:32 [playlist_mainstream:3] Playlist treated as format application/x-mpegURL
2021/08/03 17:17:32 [playlist_mainstream:3] Successfully loaded a playlist of 195 tracks.
2021/08/03 17:17:32 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/mainstream/media/Summer/Surf Mesa - ily  i love you baby.mp3".
2021/08/03 17:17:32 [clock.wallclock_main:2] We must catchup 17.94 seconds!
2021/08/03 17:17:33 [clock.wallclock_main:2] We must catchup 18.53 seconds!
2021/08/03 17:17:35 [clock.wallclock_main:2] We must catchup 19.34 seconds!
2021/08/03 17:17:36 [clock.wallclock_main:2] We must catchup 20.08 seconds!
2021/08/03 17:17:37 [clock.wallclock_main:2] We must catchup 20.80 seconds!
`

**Comment by SC2Mitch** [comment]
The `We must catchup %% seconds!` indicates your system is running behind and or is suffering performance issues, please review your system CPU and memory usage.

**Comment by ReavMC** [comment]
Hi!

We have a Root Server with 8 Cores and 4GB RAM. The CPU is a AMD EPYC 7742.
Do we need more RAM? Befor the resett of our Root Server Azuracast doesent had any Problems. Now with the v0.13.0 the Problme came.

![Unbenannt](https://user-images.githubusercontent.com/63062134/128321410-e99678b2-a528-4de0-bd1a-1cb016fbc528.PNG)

**Comment by Vaalyn** [comment]
I would definitely recommend adding more memory since your server is using 100% of the available swap space (although there is a good chunk of RAM that is only cached which should be cleared by the OS automatically).

Using swap space instead of RAM will lead to CPU issues due to the slowness of the HDD where the swap is located.

Could you also look into the output of `top` instead of `htop` to retrieve more detailed CPU load data like `%st`, `%wa`, etc.?

I would also be interested in the list of running process sorted by memory usage to see what is using the memory as well as how many stations you are running to get a feel for the size of the installation.

**Comment by ReavMC** [comment]
> 
> 
> I would definitely recommend adding more memory since your server is using 100% of the available swap space (although there is a good chunk of RAM that is only cached which should be cleared by the OS automatically).
> 
> Using swap space instead of RAM will lead to CPU issues due to the slowness of the HDD where the swap is located.
> 
> Could you also look into the output of `top` instead of `htop` to retrieve more detailed CPU load data like `%st`, `%wa`, etc.?
> 
> I would also be interested in the list of running process sorted by memory usage to see what is using the memory as well as how many stations you are running to get a feel for the size of the installation.

I have only 1 Station. Also i have some TS3AudioBots online (but they are more on CPU) and a TeamSpeak 3 Server

**Comment by ivellios1988** [comment]
Try stopping any of these processes and then check if this fixed your issue with AzuraCast.

**Comment by ReavMC** [comment]
> Try stopping any of these processes and then check if this fixed your issue with AzuraCast.

I tryed it and it doesent work :/
Sry for my Bad english.
Can i install an oder version of Azuracast like the 0.12.4 ?

**Comment by Abqehebter** [comment]
@ReavMC Check out the latest version 0.14

**Comment by ReavMC** [comment]
> 
> 
> @ReavMC Check out the latest version 0.14

done it now i dont have an error in Liquidsoap but in Icecast:

`[2021-08-07  15:58:16] WARN connection/get_ssl_certificate Invalid private key file /etc/nginx/certs/default.key (system lib)
[2021-08-07  15:58:16] WARN slave/slave_startup process has 65536 max file descriptor limit`

**Comment by SC2Mitch** [comment]
That's not a error, and it's nothing to be worried about, it's just a warning.

**Comment by AndreBlin** [comment]
Good morning, I have a very similar problem. In the stable version 0.12.x everything went wonderfully. After I updated to 0.13, the Azura doesnt connect to LautFM.  I switched back to 0.12.x. With the current version 0.14 the problem is still there.

2021/08/11 10:05:50 [relay_1:3] Connecting mount /netlabel_org for source@netlabelorg.stream.laut.fm...
2021/08/11 10:05:50 [relay_1:2] Connection failed: SSL connection() error: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
strange error flushing buffer ... 
2021/08/11 10:05:50 [relay_1:3] Will try again in 3.00 sec.

Best regards

**Comment by LeonLionFM** [comment]
Hey, yes I have the same problem. The metadata just stops being sent at some point and everything stops. The last played song is then just permanently there.

The good thing: The normal stream continues to run. But the metadata is annoying.

**Comment by Vaalyn** [comment]
@LeonLionFM do you have the same error mentioned in the previous post?

```
Connection failed: SSL connection() error: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

**Comment by LeonLionFM** [comment]
@Vaalyn But this station here from Andre:

```
2021/08/11 10:05:50 [relay_1:3] Connecting mount /netlabel_org for source@netlabelorg.stream.laut.fm...
2021/08/11 10:05:50 [relay_1:2] Connection failed: SSL connection() error: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
strange error flushing buffer ...
2021/08/11 10:05:50 [relay_1:3] Will try again in 3.00 sec.
```
...has been connected to SSL on server 1. I can try to reproduce the whole thing again if needed.
Currently I am connected there without SSL, that's probably why it works for me.

**Comment by Vaalyn** [comment]
This looks like there is something in their setup in relation to their SSL which might be causing this.
There is not much public information from Laut.FM about their servers and we don't have access to a Laut.FM account so there is not much we can directly test.

Is it possible to use plain http to connect the relay to their stream?
(From your writing it seems like it is, just want to confirm my assumption)

If this is the case then it might be a workaround to this error until it's figured out and fixed.

I have seen some bug fixes in the Liquidsoap 2.0.0 beta version in regards to SSL with SNI. Not sure if this might be related but it could be that it is and could solve the problem when that version is released.

**Comment by LeonLionFM** [comment]
Yes, that's exactly how it is. I currently use http instead of https everywhere with AzuraCast. So everything works so far for now, except for server 3 - More or less.

I'm also very much into Liquidsoap 2.0 at the moment and hope that it will fix a lot of bugs regarding SSL.

**Comment by SlvrEagle23** [comment]
I've seen this same issue on my installation. It's very rare, but it occasionally happens that Liquidsoap somehow loses the metadata connection, but keeps streaming the actual stream, just never updating the metadata along with it; to fix it, restarting the entire stream is required.

I'm hoping this is fixed or at least partly mitigated by our upcoming upgrade to Liquidsoap 2.0.

**Comment by LeonLionFM** [comment]
Yes, that's how I did it. Simply restart Liquidsoap, then everything went again for the time being. Thanks!

**Comment by AndreBlin** [comment]
Hi Leon
Ich nehme an, ich kann Dir auch auf Deutsch schreiben. Kannst Du mir bitte einen Screenshot Deiner Konfig von AC schicken.
Ich habe nun alles durch und komme nicht ein Stück weiter. Selbst die Neustarts haben nicht geholfen.

Beste Grüße


> 
> 
> Yes, that's how I did it. Simply restart Liquidsoap, then everything went again for the time being. Thanks!

**Comment by LeonLionFM** [comment]
Hallo @AndreBlin 

Klar! Hier:
![grafik](https://user-images.githubusercontent.com/88619559/130272926-30e9b2ca-e4a5-4f26-b893-f331bcc27a20.png)
![grafik](https://user-images.githubusercontent.com/88619559/130272958-2c4222b6-58f3-457e-a259-4351864fb749.png)

**Comment by AndreBlin** [comment]
Vielen Dank für die rasche Antwort....
Ich hatte heute Nachmittag das Upgrade gemacht und ausser einem Neustart nichts weíter gemacht. 
Nach einer "Weile" scheinen sich der Sender / Server und LautFM verständigt zu haben. 

**->> Problem solved for now <<-**

Beste Grüße

**Comment by LeonLionFM** [comment]
Freut mich das es nun geklappt hat!
Ich nehme die Screens mal wieder raus. LautFM-Sachen sollten auch dort bleiben 🙂

**Comment by rexjohannes** [comment]
Gibt auch im Laut Forum ne Anleitung: https://forum.laut.fm/t/azuracast-lautfm-einbindung/11671
