### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by ncfernan** [AzuraCast/AzuraCast#4833]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #784438f (2021-11-19 21:30) • Docker • PHP 8.0

### What happened?

When I installed the version I'm using now the memory footprint was 1.9GB (46%) and now it is 3.1GB (77%):

![image](https://user-images.githubusercontent.com/10008844/144610695-0fbc6c51-a94a-4bb5-a4b9-3e9ac06e1b7f.png)

Another thing that caught my attention was the CPU consumption:

![image](https://user-images.githubusercontent.com/10008844/144610846-55e38bc4-41bf-49eb-8e2e-b3df6578867d.png)

The stable release managed to keep both figures below 0.8

By the way, it would be nice to have a log for these figures, to see the evolution of each marker over time.

**Comment by ncfernan** [comment]
22 minutes later...  another memory usage increase

![image](https://user-images.githubusercontent.com/10008844/144615148-8c865ed0-e7dd-40ed-b1c4-ac3bcfaf2f30.png)

**Comment by Abqehebter** [comment]
I can not confirm. AzuraCast consumes the least for me.
However, you have to take into account that new versions and features are not cheaper in terms of RAM and the like.

Are there any anomalies in the AzuraCast logs?

**Comment by ncfernan** [comment]
Liam, I have 4 stations and they are working good, despite that issue I reported of randomly missing cover art.

The 1.9GB footprint I observed when I updated to the current rolling release. After some days (I don't know how to see the uptime of the stations or Azuracast) the figures were 50% higher. It is the same release.

If you give me directions on how to collect the info you need for your analysis, just say it. I can restart any station, the Azuracast or the Linux box anytime you need.

**Comment by SC2Mitch** [comment]
Hi there, 

I'm currently reviewing this issue now, can you give us the exact details of your server so i can try and replicate it on my side? Such as stations, how many songs are in each station, playlist details, etc.

Along with this, can you provide server information, such as CPU cores, memory and storage? 

Cheers.

**Comment by ncfernan** [comment]
Hi Mitch, do you want to access my Linux box?  I can open SSH for you. You can do anything you need to track the issue, I have a fresh backup of the entire VM taken this morning.

**Comment by SC2Mitch** [comment]
If you can reach out to me on the AzuraCast Discord, we can talk in DMs about looking into your machine. https://azuracast.com/discord

**Comment by ncfernan** [comment]
The situation is getting worse...  now the music stops from time to time

![image](https://user-images.githubusercontent.com/10008844/144724493-c947b51d-ce7b-4cca-8b02-eb27b33318d0.png)

![image](https://user-images.githubusercontent.com/10008844/144724510-ec3f1133-e979-49ea-b588-a7231cdcf2c6.png)

My VM has 2 cores and 4GB of memory. It's hosted at Linode.

![image](https://user-images.githubusercontent.com/10008844/144724576-8f230a06-29a1-4c99-9441-1bba7d3b559b.png)

![image](https://user-images.githubusercontent.com/10008844/144724587-15fe9a5b-c8fe-4497-a7e4-f9d4dc17c895.png)

It may be a coincidence, but the CPU usage increased with the current rolling release.

![image](https://user-images.githubusercontent.com/10008844/144724625-50a92849-d025-42af-a3e8-25070f6efa34.png)

**Comment by ncfernan** [comment]
Just updated to `Rolling Release #d20277a (2021-12-04 23:38) • Docker • PHP 8.0`

![image](https://user-images.githubusercontent.com/10008844/144749133-ef52aebe-2248-436d-83cf-7d53a64a71d9.png)

![image](https://user-images.githubusercontent.com/10008844/144749158-e8604b30-4db3-4d8a-958c-f0ea4a21e4c1.png)

**Comment by ncfernan** [comment]
After 16 minutes... the stations stopped

![image](https://user-images.githubusercontent.com/10008844/144749383-bc1d74c8-5cee-4ec5-8504-24c8d7afcec5.png)

![image](https://user-images.githubusercontent.com/10008844/144749395-382e9c64-d1d8-4be5-804c-6fd0951147b3.png)

**Comment by ncfernan** [comment]
How do I go back to the stable release?

**Comment by Abqehebter** [comment]
Backups helped me a lot back then to get back one version. That's why I make some too.

But here it would be explained also again differently: https://docs.azuracast.com/en/getting-started/updates/release-channels

**Comment by ncfernan** [comment]
Liam, I was using the stable version until mid November, then I installed 3 rolling version. My backups are daily, weekly and monthly. Unfortunately the oldest one is from 2021-11-21, after the first rolling version.

I guess I cannot install the stable version over the rolling version because there was migration of some components, so the downgrade may render my Azuracast unusable.

**Comment by SC2Mitch** [comment]
From your last picture it seems to be fine now, I'm unable to find a reason as to what's causing the spikes nor has there been other reports from liquid soap users about memory leaks. 2gb to 4gb is fairly standard memory usage.

**Comment by ncfernan** [comment]
Mitch, the memory leak was the first thing I thought was causing the increase in memory usage from 2.0 to 3.2 GB. Let's see how the latest version behaves. I'll keep you posted here.

By the way, did you connect to my Azuracast?  Did you find anything that could help your investigation?

**Comment by Abqehebter** [comment]
@SC2Mitch I can confirm this. I have 15 stations running here and have not suffered any major memory problems due to AzuraCast. That's why I don't understand how this happens.

@ncfernan At this point I can only recommend to reinstall AzuraCast completely (I can also use the stable version, which is recommended for live operation anyway).

**Comment by SC2Mitch** [comment]
> Mitch, the memory leak was the first thing I thought was causing the increase in memory usage from 2.0 to 3.2 GB. Let's see how the latest version behaves. I'll keep you posted here.
> 
> By the way, did you connect to my Azuracast?  Did you find anything that could help your investigation?

I reviewed your machine and found nothing of a huge concern that'd warrant high memory usages, a few stations with minimal playlists, but the stations themselves had high media volumes (that shouldn't be a issue anyway).

I'll be home again tonight to have a deep look at the logs to see if anything is up.

**Comment by ncfernan** [comment]
Follow up after 4 hours:

![image](https://user-images.githubusercontent.com/10008844/144757249-ecab929c-d899-4bd9-a72d-1f9c6991133f.png)

![image](https://user-images.githubusercontent.com/10008844/144757262-55e1eb3c-b596-4680-9067-ca7cc25a4d6c.png)

**Comment by ncfernan** [comment]
@SC2Mitch , I think I have a clue on what's happening. I'm editing some filenames to add the release year, for example:

From `Bee Gees - You win again.mp3` to `Bee Gees - You win again [1987].mp3`

There are about 300 renamed files in 5K files, BUT the playlist still has the old names. Do you think this may be the cause of the high CPU usage by mySQL and LiquidSoap?  The playlist has filenames that don't exist anymore.

My Linux box is so unstable right now that I cannot listen to any station. I'll let my installation as is for you to analyze and tomorrow I'll load new playlists to see if that fixes the problem.

If you need more time to investigate or full Linux access, just let me know.

**Comment by Vaalyn** [comment]
@ncfernan I notice a very high `st` value in your `top` screenshots.
The high CPU load seems to come from this. The `st` value shows you how much CPU time was "stolen" from your VM by the Hypervisor. A lot of shared VM hosters will use this "stealing" of CPU time in order to prevent someone on the shared machine from constantly consuming a lot of resources. There is nothing that we can do about CPU stealing so if this persists you should look into moving the VM over to one where they assign you the resources exclusively.

If the RAM usage only increases while you are renaming / editing files this might be the cause of the increase. This increase should go down after all media are reprocessed though. Are you renaming the files through the web interface or directly on the disk?

**Comment by ncfernan** [comment]
@Vaalyn you are right. I just contacted Linode and they did a live migration to another host. The CPU time dropped to the levels I used to see:

![image](https://user-images.githubusercontent.com/10008844/144850958-a96f0e67-939f-40df-8498-8144d24a2204.png)

Now I'm waiting to see if the memory footprint shrinks by itself. I created and uploaded new playlists with files that actually are in the vault, so if the problem was related to missing files, it should work now.

![image](https://user-images.githubusercontent.com/10008844/144851038-a2585902-c93f-402f-978f-35e70f1869e7.png)

I used Centova for 10 years before switching to Azuracast and when I changed some filenames it simply skipped those files that were not in the filesystems and jumped to the next in queue. I thought that I wouldn't have any problem of this kind with Azuracast.

**Comment by ncfernan** [comment]
> Are you renaming the files through the web interface or directly on the disk?

I prepare all files and playlists in Win10 and then mirror to Azuracast box (using FreeFileSync). The playlists are created using I program I wrote and manually inserted into each station.

The renaming process (using Mp3tag) also fixes some bad cover art and other metadata as well (album name, date, misspelled song and artist names).

**Comment by NicoxDJ** [comment]
I've been facing the same memory issue on Raspberry PI. One friend told me that all problems came from the new Ubuntu kernel 1046 (actually since 2 days there is newer one (1047), but didn't fix anything). For me even the whole device is bricked, and I have to hard reset it.

**Comment by ncfernan** [comment]
Follow up on memory usage:

![image](https://user-images.githubusercontent.com/10008844/145026518-f2719972-fb78-4550-b6a9-562a43407de2.png)

![image](https://user-images.githubusercontent.com/10008844/145026577-d29c958e-8c98-4485-8c64-e1da38c25e61.png)

![image](https://user-images.githubusercontent.com/10008844/145026604-aea6dced-6c0c-413b-95fb-eb7f3c51bb78.png)

Anything unusual?

**Comment by ncfernan** [comment]
Follow up after almost 3 days:

![image](https://user-images.githubusercontent.com/10008844/145204018-3df5aebb-7f75-4e91-bf97-3b4ee9f10ef5.png)

![image](https://user-images.githubusercontent.com/10008844/145204054-f21a8971-d8ab-4f35-a622-763623863059.png)

![image](https://user-images.githubusercontent.com/10008844/145204083-ad4f8800-5900-4e3a-8baa-6121aa34b423.png)

**Comment by SC2Mitch** [comment]
I believe this is working within parameters and there's no memory leak with AzuraCast nor Liquidsoap. The memory may be a bit high, yes, but this is intended. Should you have any other concerns, let me know.

**Comment by adoboligh1** [comment]
same issue here, azuracast has been very bad at peformance lately

**Comment by SlvrEagle23** [comment]
> same issue here, azuracast has been very bad at peformance lately

Please avoid making broad, unsubstantiated statements like this, because it simultaneously does two things:
 - It misleads people into thinking AzuraCast is "bloating" beyond its previous size, when in fact it's remained very similar to its previous size and has even _removed_ some components to optimize speed, and
 - It gives us a problem to worry about, but not the information we need to confirm or even begin to fix it.

**Comment by ncfernan** [comment]
Hi guys. I don't want to be boring, but the memory usage is getting worse and sometimes the stations just stop broadcasting. I know that Mitch said it was intended, but I cannot believe that you code a program to use all memory on purpose. When restarted, Azuracast takes about 2.1 GB (52%), and now it is approaching 99% percent. Something definitely must be wrong.

![image](https://user-images.githubusercontent.com/10008844/149329358-687458ca-dea0-4973-8622-81324bbfc9a8.png)

![image](https://user-images.githubusercontent.com/10008844/149329402-2c08acc6-2943-43de-84c4-72b1b7742270.png)

![image](https://user-images.githubusercontent.com/10008844/149329663-861a87d5-6183-43c7-94ed-cff4e4fec9a0.png)

I'm using the latest Rolling Release (2022-01-04). It's the most memory demanding version so far.

**Comment by SC2Mitch** [comment]
Create a new issue please, it'll be hard to track busy issue topics like this with 20+ replies.

**Comment by superlinuxero** [comment]
In my test server, a pi4 with 4GB RAM, high RAM usage's been always there, in the main liquidsoap process, every 20 seconds aprox, cpu and ram go to limits and I do not understand why it happens, since my test server just holds 1 playlist and 10 songs.

However, after doing an ./update.sh to that test server mariadb cpu and ram usage skyrockets every 20 seconds or so, making the whole system unresponsive and a hard reset necessary in a matter of hours. Doing a new installation with that same rolling release I used to upgrade does not show the problem, so I'm assuming for now that the problem arises when going though ./update.sh . Doing a recovery from last night's back up and mariadb usage comes to normal

Interestingly, doing an ./update --full does the upgrade alright and mariadb stays normal as expected after an update

**Comment by superlinuxero** [comment]
In my latest pretty much everything works like a charm.

After my previous tests (see message above), not being happy with the fact that liquidsoap still goes up to the RAM till aprox. 3.30GB RAM usage every 20 seconds, I deleted my rolling release installation using the uninstall.sh command. I also had to delete the /var/azuracast folder and the database in mysql.

Then I installed stable release version 0.15.2. So far so good: no more wasted RAM and CPU. Haven't tried updating yet as there is no new stable version yet. The only 2 things taht do not work yet (didn't work in the rolling release either): _On the Air_ not showing currently played song, and album art not showing, even though my last.fm api key has been inserted.

![image](https://user-images.githubusercontent.com/32478929/158328402-97085378-d7b4-4871-8254-cd44925fda06.png)

![image](https://user-images.githubusercontent.com/32478929/158328502-1dab15bb-4cf0-4238-a7ab-3478d43c5f39.png)
