### ISSUE TITLE
Metadata Manager returns error: Atom at offset 2068037 claims to go beyond end-of-file

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#4896]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

3a7e457

### What happened?

Files are unable to be processed, the issue appears to be related to Metadata Manager

But when I go to the station in question and check under unprocessable files, it shows nothing. 

![image](https://user-images.githubusercontent.com/29955942/146681504-4ae45ca5-dc20-48f1-9967-feb68b896ac1.png)

### Relevant log output

```shell
web_1                      | [2021-12-19T02:25:05.551969+00:00] AzuraCast.ERROR: Handling "App\Message\AddNewMediaMessage" failed: The command "'/usr/bin/php8.1' '/var/azuracast/www/vendor/bin/metadata-manager' 'read' '/var/azuracast/stations/amiga/media/dantes_kitchen_(skinflick_remix).mp3' '/tmp/metadata_k0iAKu.json' '/tmp/metadata_ktLygy.jpg'" failed.  Exit Code: 1(General error)  Working directory: /etc/runit/runsvdir/default/php-worker  Output: ================   [ERROR] Cannot process media at path dantes_kitchen_(skinflick_remix): ["Atom            at offset 488132 claims to go beyond end-of-file (length: 159571                 bytes)"]                                                                   Error Output: ================  {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":129,"code":0} []
web_1                      | [2021-12-19T02:25:06.403764+00:00] AzuraCast.ERROR: Handling "App\Message\AddNewMediaMessage" failed: The command "'/usr/bin/php8.1' '/var/azuracast/www/vendor/bin/metadata-manager' 'read' '/var/azuracast/stations/amiga/media/compression_(the_absent).mp3' '/tmp/metadata_ozyORy.json' '/tmp/metadata_pt9zbv.jpg'" failed.  Exit Code: 1(General error)  Working directory: /etc/runit/runsvdir/default/php-worker  Output: ================   [ERROR] Cannot process media at path compression_(the_absent): ["Atom at offset          1780692 claims to go beyond end-of-file (length: 159472 bytes)"]           Error Output: ================  {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":129,"code":0} []
web_1                      | [2021-12-19T02:25:07.011667+00:00] AzuraCast.ERROR: Handling "App\Message\AddNewMediaMessage" failed: The command "'/usr/bin/php8.1' '/var/azuracast/www/vendor/bin/metadata-manager' 'read' '/var/azuracast/stations/amiga/media/the_house_of_usher_-_succubus_(extended).mp3' '/tmp/metadata_W2KbNv.json' '/tmp/metadata_4vvYtv.jpg'" failed.  Exit Code: 1(General error)  Working directory: /etc/runit/runsvdir/default/php-worker  Output: ================   [ERROR] Cannot process media at path the_house_of_usher_-_succubus_(extended):           ["Atom at offset 2068037 claims to go beyond end-of-file (length:                156768 bytes)"]                                                            Error Output: ================  {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":129,"code":0} []
```

**Comment by Vaalyn** [comment]
This looks like an error that should already be fixed in getid3: https://github.com/JamesHeinrich/getID3/issues/219

Would you mind sending me one of those 3 files from the log so I can check out the content of the files as well as what happens on the latest release of getid3.

**Comment by SC2Mitch** [comment]
@Vaalyn Here we go, the other files aren't reading errors anymore, here's the one that remains with this error: 

web_1                      | [2021-12-20T22:20:07.366558+00:00] AzuraCast.ERROR: Handling "App\Message\AddNewMediaMessage" failed: The command "'/usr/bin/php8.1' '/var/azuracast/www/vendor/bin/metadata-manager' 'read' '/var/azuracast/stations/amiga/media/the_house_of_usher_-_succubus_(extended).mp3' '/tmp/metadata_K2cSci.json' '/tmp/metadata_YXPnUg.jpg'" failed.  Exit Code: 1(General error)  Working directory: /etc/runit/runsvdir/default/php-worker  Output: ================   [ERROR] Cannot process media at path the_house_of_usher_-_succubus_(extended):           ["Atom at offset 2068037 claims to go beyond end-of-file (length:                156768 bytes)"]                  

https://www.upload.ee/files/13732182/the_house_of_usher_-_succubus__extended_.mp3.html

**Comment by SlvrEagle23** [comment]
@SC2Mitch I've updated the Metadata Manager dependency inside AzuraCast to reference the newer build channel of the GetID3 library; let me know if that helps with this issue.

**Comment by SC2Mitch** [comment]
Yeah I'm also able to verify it doesn't fix the issue, I'll just remove the file, as it's only a single file and we've had no extra reports of broken files.
