### ISSUE TITLE
Installation is exiting

### ISSUE THREAD

**Issue by joshuasundar** [AzuraCast/AzuraCast#5251]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### What happened?

I am trying to use the steps from the following documentation,
https://docs.azuracast.com/en/getting-started/installation/docker

But after running the command,
./docker.sh install

it keeps showing the same message.
<img width="1158" alt="Screenshot 2022-04-01 at 7 43 26 AM" src="https://user-images.githubusercontent.com/23213729/161181036-71c69bd2-4389-4adf-8edf-b4c2e7988900.png">

I tried different steps 
- Rolling Release Channel
- Stable Channel

But I am getting the same message.

**Comment by SlvrEagle23** [comment]
@joshuasundar This should be fixed as of the latest Rolling Release that just released this evening. Try running:

```
./docker.sh update-self
```

and then running the installation again.

**Comment by simpsss** [comment]
Checking installation requirements for AzuraCast...
[PASS] Operating System: Linux
[PASS] Architecture: x86_64
[PASS] Command Present: curl
[PASS] Command Present: awk
[PASS] User Permissions
[PASS] Installation Directory
[PASS] All requirements met!
Docker is already installed! Continuing...
Docker Compose is already installed. Continuing...

> @joshuasundar This should be fixed as of the latest Rolling Release that just released this evening. Try running:
> 
> ```
> ./docker.sh update-self
> ```
> 
> and then running the installation again.

Checking installation requirements for AzuraCast...
[PASS] Operating System: Linux
[PASS] Architecture: x86_64
[PASS] Command Present: curl
[PASS] Command Present: awk
[PASS] User Permissions
[PASS] Installation Directory
[PASS] All requirements met!
Docker is already installed! Continuing...
Docker Compose is already installed. Continuing...

**Comment by alexoldie** [comment]
Here also the same install error

**Comment by joshuasundar** [comment]
> @joshuasundar This should be fixed as of the latest Rolling Release that just released this evening. Try running:
> 
> ```
> ./docker.sh update-self
> ```
> 
> and then running the installation again.

@SlvrEagle23 
I am not sure if I am doing anything wrong. But it is still the same.

<img width="1007" alt="Screenshot 2022-04-01 at 7 21 12 PM" src="https://user-images.githubusercontent.com/23213729/161277231-c529e725-e4a5-472f-8462-fbd5af33bbf8.png">

**Comment by AliseFonero** [comment]
@joshuasundar the same, same errors

**Comment by SlvrEagle23** [comment]
Sorry about that folks! Try running:

```
./docker.sh update-self
```

and then the installation should complete without issue.
