### ISSUE TITLE
After updating from 0.15.2 to Latest, listener data is missing and isn't recorded properly. 

### ISSUE THREAD

**Issue by balmasedano** [AzuraCast/AzuraCast#5622]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.2

### What happened?

A month ago, I updated from 0.15.2 to 0.17.1 version using the stable channel. I lost my home page statistics graphic and also station pages graphics by day.

<img width="1164" alt="Captura de Pantalla 2022-07-25 a las 10 48 05" src="https://user-images.githubusercontent.com/2371754/180739194-0b4f7a7c-a1b6-4d91-8529-238d35e2a86d.png">

Then, I updated to the newer stable 0.17.2 and I still had the same problem: the info ends at June 30th.

Is there any solution without reinstalling? I don't know what log should I paste to see where is the error.

Thanks!

**Comment by ItsMitchh** [comment]
I'm not sure as to what'd cause this, possibly something with MySQL or how we collect listener metrics. Will flag up.

**Comment by balmasedano** [comment]
Hi, @ItsMitchh! The possible bug persists also when updating to 0.17.3. Now I can't see any data.

<img width="1140" alt="Captura de Pantalla 2022-08-15 a las 10 17 18" src="https://user-images.githubusercontent.com/2371754/184600772-d2f95918-e89c-48b3-8f00-aa840f3aaa38.png">

Also on internal statistic pages.

<img width="1306" alt="Captura de Pantalla 2022-08-15 a las 10 19 14" src="https://user-images.githubusercontent.com/2371754/184601033-77c86924-73c4-4777-8f45-0b4cfab29eef.png">

**Comment by balmasedano** [comment]
I don't know if it's related to this bug. But, when I access to sync tasks, I've seen that 'RunAnalyticsTask' has never executed. If I try to do it manually, the page freezes and never displays any error.

@ItsMitchh, which log or logs can I see to paste the possible errors?

<img width="995" alt="Captura de pantalla 2022-10-07 a las 12 28 35" src="https://user-images.githubusercontent.com/2371754/194534886-198ae77f-653c-4f60-9ba0-b3ad5318b1f8.png">

**Comment by balmasedano** [comment]
After updating to 0.17.3, stats graphics started working again, but slowly: some days didn't appear. Then, I lost the NowPlaying data and had problems again when updating to 0.17.4. After reinstalling and restoring a backup, RunAnalyticsTask stopped working again and graphics didn't regenerate again.

When I execute the task manually I get an 'Slim Application Error'.

I've modified values in azuracast.env file to bigger ones, but nothing.

> [2022-11-07T13:00:44.232352+00:00] AzuraCast.ERROR: Symfony\Component\Process\Exception\ProcessTimedOutException: The process "'php' '/var/azuracast/www/bin/console' 'azuracast:sync:task' 'App\Sync\Task\RunAnalyticsTask'" exceeded the timeout of 3400 seconds. (uncaught exception) at /var/azuracast/www/vendor/symfony/process/Process.php line 1152 while running console command `azuracast:sync:run` {"exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessTimedOutException(code: 0): The process \"'php' '/var/azuracast/www/bin/console' 'azuracast:sync:task' 'App\\Sync\\Task\\RunAnalyticsTask'\" exceeded the timeout of 3400 seconds. at /var/azuracast/www/vendor/symfony/process/Process.php:1152)"} []

Thanks!

<img width="1076" alt="Captura de pantalla 2022-11-07 a las 20 54 23" src="https://user-images.githubusercontent.com/2371754/200402193-920bca7a-f3ad-4b31-be36-8b0547d359c6.png">

**Comment by Vaalyn** [comment]
Hey, the manual running of sync tasks was bugged and got fixed yesterday so it shouldn't result in a `Slim Application Error` anymore.

Regarding the general issue here, I suspect that due to the high number of listeners you probably have a lot of analytics data in your database which causes the sync task to time out (as seen in the error you posted).

In version 0.17.1 we released an overhaul of the station statistics pages which also included a restructuring of the listeners data If I remember correctly. I'm not sure why this would break the displaying of analytics data though. 🤔 

The `RunAnalyticsTask` that is timing out is processing only the data for the last 5 days so for it to time out after over 50 minutes looks like there is some performance issue in the analytics aggregation for large listener bases. Will need to investigate this.

**Comment by balmasedano** [comment]
Hi @Vaalyn!

I still have the same problem with the 0.17.7 stable version. I also restored a simple backup of my dedicated server with Azuracast in an easier VPS. After installing the copy, all stats work fine, but with no listeners, for obvious reasons.

Should I increase processing times on azuracast.env for some services?

`[2023-02-12T00:04:02.805490+00:00] AzuraCast.ERROR: Symfony\Component\Process\Exception\ProcessTimedOutException: The process "'php' '/var/azuracast/www/bin/console' 'azuracast:sync:task' 'App\Sync\Task\RunAnalyticsTask'" exceeded the timeout of 3600 seconds. (uncaught exception) at /var/azuracast/www/vendor/symfony/process/Process.php line 1152 while running console command `azuracast:sync:run` {"exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessTimedOutException(code: 0): The process \"'php' '/var/azuracast/www/bin/console' 'azuracast:sync:task' 'App\\Sync\\Task\\RunAnalyticsTask'\" exceeded the timeout of 3600 seconds. at /var/azuracast/www/vendor/symfony/process/Process.php:1152)"} []
`

**Comment by pavlos2** [comment]
Is this solved? I experience the same issue.

**Comment by balmasedano** [comment]
@pavlos2 I'm currently using the 0.19.1 stable version and it's completely solved.

**Comment by pavlos2** [comment]
@balmasedano, thank you! I think I managed to fix the issue by increasing the EXECUTION_TIME in azuracast.env. Time will tell...
