### ISSUE TITLE
API /station/{station_id}/schedule returns odd results

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6685]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #1ea88fe (2023-10-14 0:27)

### What happened?

Getting schedule data using `start` and `end` parameters returns some odd results, maybe we could talk this out.

I put some testing code up at https://github.com/Moonbase59/azuracast_xmltv/blob/master/test/get_schedule.py, where the problems are demonstrated.

**Comment by BusterNeece** [comment]
@Moonbase59 This should be fixed as of newer versions of the codebase. I found and fixed an issue where we were padding the date range you specified by a day or so on both sides (this is necessary for us to *fetch* events in that range, but not to *display* them) and that's been fixed.

**Comment by Moonbase59** [comment]
Yep, I’ve seen your changes but there are still errors, so I assumed you’re still working on it. You might want to try the three (?) examples given in https://github.com/Moonbase59/azuracast_xmltv/blob/master/test/get_schedule.py.

**Comment by BusterNeece** [comment]
@Moonbase59 the custom timezone thing is a known issue. It takes any timezone data you provide in the datetime ranges and discards it, I believe because of an issue with earlier versions of the Fullcalendar library we use for the week display. This may merit some investigation on our end to see if it's still a thing we need to be doing.

Do the other ones work? i.e. supplying just dates?

**Comment by BusterNeece** [comment]
@Moonbase59 Not sure what you meant in your reply on this one. Is it still happening?

We can schedule a time to talk, but it's easier for me to keep track of things we've discussed if they're written down somewhere.

**Comment by Moonbase59** [comment]
Love to talk, but same here: Written down things stick …

Yep, still happens. Using a range of
```python
start = "2023-10-22"
end = "2023-10-22"
```

I get

```
2023-12-02T18:00:00+01:00 - 2023-12-03T00:00:00+01:00 Heart Dance from London, UK
2023-12-03T00:00:00+01:00 - 2023-12-03T06:00:00+01:00 Nuit électronique
2023-12-03T06:00:00+01:00 - 2023-12-03T12:00:00+01:00 Pop
2023-12-03T06:00:00+01:00 - 2023-12-03T12:00:00+01:00 Schlager
2023-12-03T12:00:00+01:00 - 2023-12-03T15:00:00+01:00 Easy Listening
2023-12-03T15:00:00+01:00 - 2023-12-03T17:00:00+01:00 New Age
2023-12-03T17:00:00+01:00 - 2023-12-03T20:00:00+01:00 Lounge
2023-12-03T20:00:00+01:00 - 2023-12-03T22:00:00+01:00 House
2023-12-03T22:00:00+01:00 - 2023-12-04T00:00:00+01:00 Goa, Psytrance
2023-12-04T00:00:00+01:00 - 2023-12-04T06:00:00+01:00 Nuit électronique
2023-12-04T06:00:00+01:00 - 2023-12-04T12:00:00+01:00 Pop
2023-12-04T12:00:00+01:00 - 2023-12-04T15:00:00+01:00 Easy Listening
2023-12-04T15:00:00+01:00 - 2023-12-04T16:00:00+01:00 Schlager
2023-12-04T16:00:00+01:00 - 2023-12-04T17:00:00+01:00 Oldies
2023-12-04T17:00:00+01:00 - 2023-12-04T18:00:00+01:00 Moonbase
2023-12-04T20:00:00+01:00 - 2023-12-04T22:00:00+01:00 Irish Pub
2023-12-04T22:00:00+01:00 - 2023-12-05T00:00:00+01:00 Folk Rock
2023-12-05T00:00:00+01:00 - 2023-12-05T06:00:00+01:00 Hard Rock
2023-12-05T06:00:00+01:00 - 2023-12-05T12:00:00+01:00 Pop
2023-12-05T12:00:00+01:00 - 2023-12-05T15:00:00+01:00 Easy Listening
2023-12-05T15:00:00+01:00 - 2023-12-05T16:00:00+01:00 Schlager
2023-12-05T16:00:00+01:00 - 2023-12-05T17:00:00+01:00 Oldies
2023-12-05T18:00:00+01:00 - 2023-12-05T20:00:00+01:00 Synthpop
2023-12-05T20:00:00+01:00 - 2023-12-05T22:00:00+01:00 Dark
2023-12-05T22:00:00+01:00 - 2023-12-06T00:00:00+01:00 Electro
2023-12-06T06:00:00+01:00 - 2023-12-06T12:00:00+01:00 Pop
2023-12-06T12:00:00+01:00 - 2023-12-06T15:00:00+01:00 Easy Listening
2023-12-06T15:00:00+01:00 - 2023-12-06T16:00:00+01:00 Schlager
2023-12-06T16:00:00+01:00 - 2023-12-06T17:00:00+01:00 Oldies
2023-12-06T18:00:00+01:00 - 2023-12-06T20:00:00+01:00 1970's Rock
2023-12-06T20:00:00+01:00 - 2023-12-06T22:00:00+01:00 Glam Rock
2023-12-06T22:00:00+01:00 - 2023-12-07T00:00:00+01:00 Southern Rock
2023-12-07T06:00:00+01:00 - 2023-12-07T12:00:00+01:00 Pop
2023-12-07T12:00:00+01:00 - 2023-12-07T15:00:00+01:00 Easy Listening
2023-12-07T15:00:00+01:00 - 2023-12-07T16:00:00+01:00 Schlager
2023-12-07T16:00:00+01:00 - 2023-12-07T17:00:00+01:00 Oldies
2023-12-07T20:00:00+01:00 - 2023-12-07T22:00:00+01:00 Krautrock
2023-12-07T22:00:00+01:00 - 2023-12-08T00:00:00+01:00 Electronic
2023-12-08T00:00:00+01:00 - 2023-12-08T06:00:00+01:00 Nuit électronique
2023-12-08T06:00:00+01:00 - 2023-12-08T12:00:00+01:00 Pop
2023-12-08T12:00:00+01:00 - 2023-12-08T15:00:00+01:00 Easy Listening
2023-12-08T15:00:00+01:00 - 2023-12-08T16:00:00+01:00 Schlager
2023-12-08T16:00:00+01:00 - 2023-12-08T17:00:00+01:00 Oldies
2023-12-08T18:00:00+01:00 - 2023-12-08T20:00:00+01:00 Hard Rock
2023-12-08T20:00:00+01:00 - 2023-12-08T22:00:00+01:00 Heavy Metal
2023-12-08T22:00:00+01:00 - 2023-12-09T00:00:00+01:00 Power Metal
2023-12-09T06:00:00+01:00 - 2023-12-09T12:00:00+01:00 Pop
2023-12-09T12:00:00+01:00 - 2023-12-09T15:00:00+01:00 Easy Listening
2023-12-09T15:00:00+01:00 - 2023-12-09T16:00:00+01:00 Schlager
2023-12-09T16:00:00+01:00 - 2023-12-09T17:00:00+01:00 Oldies
2023-12-09T18:00:00+01:00 - 2023-12-10T00:00:00+01:00 Heart Dance from London, UK
2023-12-10T00:00:00+01:00 - 2023-12-10T06:00:00+01:00 Nuit électronique
2023-12-10T06:00:00+01:00 - 2023-12-10T12:00:00+01:00 Pop
2023-12-10T06:00:00+01:00 - 2023-12-10T12:00:00+01:00 Schlager
2023-12-10T12:00:00+01:00 - 2023-12-10T15:00:00+01:00 Easy Listening
2023-12-10T15:00:00+01:00 - 2023-12-10T17:00:00+01:00 New Age
2023-12-10T17:00:00+01:00 - 2023-12-10T20:00:00+01:00 Lounge
2023-12-10T20:00:00+01:00 - 2023-12-10T22:00:00+01:00 House
2023-12-10T22:00:00+01:00 - 2023-12-11T00:00:00+01:00 Goa, Psytrance
2023-12-11T00:00:00+01:00 - 2023-12-11T06:00:00+01:00 Nuit électronique
2023-12-11T06:00:00+01:00 - 2023-12-11T12:00:00+01:00 Pop
2023-12-11T12:00:00+01:00 - 2023-12-11T15:00:00+01:00 Easy Listening
2023-12-11T15:00:00+01:00 - 2023-12-11T16:00:00+01:00 Schlager
2023-12-11T16:00:00+01:00 - 2023-12-11T17:00:00+01:00 Oldies
2023-12-11T17:00:00+01:00 - 2023-12-11T18:00:00+01:00 Moonbase
2023-12-11T20:00:00+01:00 - 2023-12-11T22:00:00+01:00 Irish Pub
2023-12-11T22:00:00+01:00 - 2023-12-12T00:00:00+01:00 Folk Rock
2023-12-12T00:00:00+01:00 - 2023-12-12T06:00:00+01:00 Hard Rock
2023-12-12T06:00:00+01:00 - 2023-12-12T12:00:00+01:00 Pop
2023-12-12T12:00:00+01:00 - 2023-12-12T15:00:00+01:00 Easy Listening
2023-12-12T15:00:00+01:00 - 2023-12-12T16:00:00+01:00 Schlager
2023-12-12T16:00:00+01:00 - 2023-12-12T17:00:00+01:00 Oldies
2023-12-12T18:00:00+01:00 - 2023-12-12T20:00:00+01:00 Synthpop
2023-12-12T20:00:00+01:00 - 2023-12-12T22:00:00+01:00 Dark
2023-12-12T22:00:00+01:00 - 2023-12-13T00:00:00+01:00 Electro
2023-12-13T06:00:00+01:00 - 2023-12-13T12:00:00+01:00 Pop
2023-12-13T12:00:00+01:00 - 2023-12-13T15:00:00+01:00 Easy Listening
2023-12-13T15:00:00+01:00 - 2023-12-13T16:00:00+01:00 Schlager
2023-12-13T16:00:00+01:00 - 2023-12-13T17:00:00+01:00 Oldies
2023-12-13T18:00:00+01:00 - 2023-12-13T20:00:00+01:00 1970's Rock
2023-12-13T20:00:00+01:00 - 2023-12-13T22:00:00+01:00 Glam Rock
2023-12-13T22:00:00+01:00 - 2023-12-14T00:00:00+01:00 Southern Rock
2023-12-14T06:00:00+01:00 - 2023-12-14T12:00:00+01:00 Pop
2023-12-14T12:00:00+01:00 - 2023-12-14T15:00:00+01:00 Easy Listening
2023-12-14T15:00:00+01:00 - 2023-12-14T16:00:00+01:00 Schlager
2023-12-14T16:00:00+01:00 - 2023-12-14T17:00:00+01:00 Oldies
2023-12-14T20:00:00+01:00 - 2023-12-14T22:00:00+01:00 Krautrock
2023-12-14T22:00:00+01:00 - 2023-12-15T00:00:00+01:00 Electronic
2023-12-15T00:00:00+01:00 - 2023-12-15T06:00:00+01:00 Nuit électronique
2023-12-15T06:00:00+01:00 - 2023-12-15T12:00:00+01:00 Pop
2023-12-15T12:00:00+01:00 - 2023-12-15T15:00:00+01:00 Easy Listening
2023-12-15T15:00:00+01:00 - 2023-12-15T16:00:00+01:00 Schlager
2023-12-15T16:00:00+01:00 - 2023-12-15T17:00:00+01:00 Oldies
2023-12-15T18:00:00+01:00 - 2023-12-15T20:00:00+01:00 Hard Rock
2023-12-15T20:00:00+01:00 - 2023-12-15T22:00:00+01:00 Heavy Metal
2023-12-15T22:00:00+01:00 - 2023-12-16T00:00:00+01:00 Power Metal
2023-12-16T06:00:00+01:00 - 2023-12-16T12:00:00+01:00 Pop
2023-12-16T12:00:00+01:00 - 2023-12-16T15:00:00+01:00 Easy Listening
2023-12-16T15:00:00+01:00 - 2023-12-16T16:00:00+01:00 Schlager
2023-12-16T16:00:00+01:00 - 2023-12-16T17:00:00+01:00 Oldies
2023-12-16T18:00:00+01:00 - 2023-12-17T00:00:00+01:00 Heart Dance from London, UK
2023-12-17T00:00:00+01:00 - 2023-12-17T06:00:00+01:00 Nuit électronique
2023-12-17T06:00:00+01:00 - 2023-12-17T12:00:00+01:00 Pop
2023-12-17T06:00:00+01:00 - 2023-12-17T12:00:00+01:00 Schlager
2023-12-17T12:00:00+01:00 - 2023-12-17T15:00:00+01:00 Easy Listening
2023-12-17T15:00:00+01:00 - 2023-12-17T17:00:00+01:00 New Age
2023-12-17T17:00:00+01:00 - 2023-12-17T20:00:00+01:00 Lounge
2023-12-17T20:00:00+01:00 - 2023-12-17T22:00:00+01:00 House
2023-12-17T22:00:00+01:00 - 2023-12-18T00:00:00+01:00 Goa, Psytrance
```

and (adapting to current dates), when using

```python
start = "2023-12-17"
end = "2023-12-17"
```

I get

```
2023-12-02T18:00:00+01:00 - 2023-12-03T00:00:00+01:00 Heart Dance from London, UK
2023-12-03T00:00:00+01:00 - 2023-12-03T06:00:00+01:00 Nuit électronique
2023-12-03T06:00:00+01:00 - 2023-12-03T12:00:00+01:00 Pop
2023-12-03T06:00:00+01:00 - 2023-12-03T12:00:00+01:00 Schlager
2023-12-03T12:00:00+01:00 - 2023-12-03T15:00:00+01:00 Easy Listening
2023-12-03T15:00:00+01:00 - 2023-12-03T17:00:00+01:00 New Age
2023-12-03T17:00:00+01:00 - 2023-12-03T20:00:00+01:00 Lounge
2023-12-03T20:00:00+01:00 - 2023-12-03T22:00:00+01:00 House
2023-12-03T22:00:00+01:00 - 2023-12-04T00:00:00+01:00 Goa, Psytrance
2023-12-04T00:00:00+01:00 - 2023-12-04T06:00:00+01:00 Nuit électronique
2023-12-04T06:00:00+01:00 - 2023-12-04T12:00:00+01:00 Pop
2023-12-04T12:00:00+01:00 - 2023-12-04T15:00:00+01:00 Easy Listening
2023-12-04T15:00:00+01:00 - 2023-12-04T16:00:00+01:00 Schlager
2023-12-04T16:00:00+01:00 - 2023-12-04T17:00:00+01:00 Oldies
2023-12-04T17:00:00+01:00 - 2023-12-04T18:00:00+01:00 Moonbase
2023-12-04T20:00:00+01:00 - 2023-12-04T22:00:00+01:00 Irish Pub
2023-12-04T22:00:00+01:00 - 2023-12-05T00:00:00+01:00 Folk Rock
2023-12-05T00:00:00+01:00 - 2023-12-05T06:00:00+01:00 Hard Rock
2023-12-05T06:00:00+01:00 - 2023-12-05T12:00:00+01:00 Pop
2023-12-05T12:00:00+01:00 - 2023-12-05T15:00:00+01:00 Easy Listening
2023-12-05T15:00:00+01:00 - 2023-12-05T16:00:00+01:00 Schlager
2023-12-05T16:00:00+01:00 - 2023-12-05T17:00:00+01:00 Oldies
2023-12-05T18:00:00+01:00 - 2023-12-05T20:00:00+01:00 Synthpop
2023-12-05T20:00:00+01:00 - 2023-12-05T22:00:00+01:00 Dark
2023-12-05T22:00:00+01:00 - 2023-12-06T00:00:00+01:00 Electro
2023-12-06T06:00:00+01:00 - 2023-12-06T12:00:00+01:00 Pop
2023-12-06T12:00:00+01:00 - 2023-12-06T15:00:00+01:00 Easy Listening
2023-12-06T15:00:00+01:00 - 2023-12-06T16:00:00+01:00 Schlager
2023-12-06T16:00:00+01:00 - 2023-12-06T17:00:00+01:00 Oldies
2023-12-06T18:00:00+01:00 - 2023-12-06T20:00:00+01:00 1970's Rock
2023-12-06T20:00:00+01:00 - 2023-12-06T22:00:00+01:00 Glam Rock
2023-12-06T22:00:00+01:00 - 2023-12-07T00:00:00+01:00 Southern Rock
2023-12-07T06:00:00+01:00 - 2023-12-07T12:00:00+01:00 Pop
2023-12-07T12:00:00+01:00 - 2023-12-07T15:00:00+01:00 Easy Listening
2023-12-07T15:00:00+01:00 - 2023-12-07T16:00:00+01:00 Schlager
2023-12-07T16:00:00+01:00 - 2023-12-07T17:00:00+01:00 Oldies
2023-12-07T20:00:00+01:00 - 2023-12-07T22:00:00+01:00 Krautrock
2023-12-07T22:00:00+01:00 - 2023-12-08T00:00:00+01:00 Electronic
2023-12-08T00:00:00+01:00 - 2023-12-08T06:00:00+01:00 Nuit électronique
2023-12-08T06:00:00+01:00 - 2023-12-08T12:00:00+01:00 Pop
2023-12-08T12:00:00+01:00 - 2023-12-08T15:00:00+01:00 Easy Listening
2023-12-08T15:00:00+01:00 - 2023-12-08T16:00:00+01:00 Schlager
2023-12-08T16:00:00+01:00 - 2023-12-08T17:00:00+01:00 Oldies
2023-12-08T18:00:00+01:00 - 2023-12-08T20:00:00+01:00 Hard Rock
2023-12-08T20:00:00+01:00 - 2023-12-08T22:00:00+01:00 Heavy Metal
2023-12-08T22:00:00+01:00 - 2023-12-09T00:00:00+01:00 Power Metal
2023-12-09T06:00:00+01:00 - 2023-12-09T12:00:00+01:00 Pop
2023-12-09T12:00:00+01:00 - 2023-12-09T15:00:00+01:00 Easy Listening
2023-12-09T15:00:00+01:00 - 2023-12-09T16:00:00+01:00 Schlager
2023-12-09T16:00:00+01:00 - 2023-12-09T17:00:00+01:00 Oldies
2023-12-09T18:00:00+01:00 - 2023-12-10T00:00:00+01:00 Heart Dance from London, UK
2023-12-10T00:00:00+01:00 - 2023-12-10T06:00:00+01:00 Nuit électronique
2023-12-10T06:00:00+01:00 - 2023-12-10T12:00:00+01:00 Pop
2023-12-10T06:00:00+01:00 - 2023-12-10T12:00:00+01:00 Schlager
2023-12-10T12:00:00+01:00 - 2023-12-10T15:00:00+01:00 Easy Listening
2023-12-10T15:00:00+01:00 - 2023-12-10T17:00:00+01:00 New Age
2023-12-10T17:00:00+01:00 - 2023-12-10T20:00:00+01:00 Lounge
2023-12-10T20:00:00+01:00 - 2023-12-10T22:00:00+01:00 House
2023-12-10T22:00:00+01:00 - 2023-12-11T00:00:00+01:00 Goa, Psytrance
2023-12-11T00:00:00+01:00 - 2023-12-11T06:00:00+01:00 Nuit électronique
2023-12-11T06:00:00+01:00 - 2023-12-11T12:00:00+01:00 Pop
2023-12-11T12:00:00+01:00 - 2023-12-11T15:00:00+01:00 Easy Listening
2023-12-11T15:00:00+01:00 - 2023-12-11T16:00:00+01:00 Schlager
2023-12-11T16:00:00+01:00 - 2023-12-11T17:00:00+01:00 Oldies
2023-12-11T17:00:00+01:00 - 2023-12-11T18:00:00+01:00 Moonbase
2023-12-11T20:00:00+01:00 - 2023-12-11T22:00:00+01:00 Irish Pub
2023-12-11T22:00:00+01:00 - 2023-12-12T00:00:00+01:00 Folk Rock
2023-12-12T00:00:00+01:00 - 2023-12-12T06:00:00+01:00 Hard Rock
2023-12-12T06:00:00+01:00 - 2023-12-12T12:00:00+01:00 Pop
2023-12-12T12:00:00+01:00 - 2023-12-12T15:00:00+01:00 Easy Listening
2023-12-12T15:00:00+01:00 - 2023-12-12T16:00:00+01:00 Schlager
2023-12-12T16:00:00+01:00 - 2023-12-12T17:00:00+01:00 Oldies
2023-12-12T18:00:00+01:00 - 2023-12-12T20:00:00+01:00 Synthpop
2023-12-12T20:00:00+01:00 - 2023-12-12T22:00:00+01:00 Dark
2023-12-12T22:00:00+01:00 - 2023-12-13T00:00:00+01:00 Electro
2023-12-13T06:00:00+01:00 - 2023-12-13T12:00:00+01:00 Pop
2023-12-13T12:00:00+01:00 - 2023-12-13T15:00:00+01:00 Easy Listening
2023-12-13T15:00:00+01:00 - 2023-12-13T16:00:00+01:00 Schlager
2023-12-13T16:00:00+01:00 - 2023-12-13T17:00:00+01:00 Oldies
2023-12-13T18:00:00+01:00 - 2023-12-13T20:00:00+01:00 1970's Rock
2023-12-13T20:00:00+01:00 - 2023-12-13T22:00:00+01:00 Glam Rock
2023-12-13T22:00:00+01:00 - 2023-12-14T00:00:00+01:00 Southern Rock
2023-12-14T06:00:00+01:00 - 2023-12-14T12:00:00+01:00 Pop
2023-12-14T12:00:00+01:00 - 2023-12-14T15:00:00+01:00 Easy Listening
2023-12-14T15:00:00+01:00 - 2023-12-14T16:00:00+01:00 Schlager
2023-12-14T16:00:00+01:00 - 2023-12-14T17:00:00+01:00 Oldies
2023-12-14T20:00:00+01:00 - 2023-12-14T22:00:00+01:00 Krautrock
2023-12-14T22:00:00+01:00 - 2023-12-15T00:00:00+01:00 Electronic
2023-12-15T00:00:00+01:00 - 2023-12-15T06:00:00+01:00 Nuit électronique
2023-12-15T06:00:00+01:00 - 2023-12-15T12:00:00+01:00 Pop
2023-12-15T12:00:00+01:00 - 2023-12-15T15:00:00+01:00 Easy Listening
2023-12-15T15:00:00+01:00 - 2023-12-15T16:00:00+01:00 Schlager
2023-12-15T16:00:00+01:00 - 2023-12-15T17:00:00+01:00 Oldies
2023-12-15T18:00:00+01:00 - 2023-12-15T20:00:00+01:00 Hard Rock
2023-12-15T20:00:00+01:00 - 2023-12-15T22:00:00+01:00 Heavy Metal
2023-12-15T22:00:00+01:00 - 2023-12-16T00:00:00+01:00 Power Metal
2023-12-16T06:00:00+01:00 - 2023-12-16T12:00:00+01:00 Pop
2023-12-16T12:00:00+01:00 - 2023-12-16T15:00:00+01:00 Easy Listening
2023-12-16T15:00:00+01:00 - 2023-12-16T16:00:00+01:00 Schlager
2023-12-16T16:00:00+01:00 - 2023-12-16T17:00:00+01:00 Oldies
2023-12-16T18:00:00+01:00 - 2023-12-17T00:00:00+01:00 Heart Dance from London, UK
2023-12-17T00:00:00+01:00 - 2023-12-17T06:00:00+01:00 Nuit électronique
2023-12-17T06:00:00+01:00 - 2023-12-17T12:00:00+01:00 Pop
2023-12-17T06:00:00+01:00 - 2023-12-17T12:00:00+01:00 Schlager
2023-12-17T12:00:00+01:00 - 2023-12-17T15:00:00+01:00 Easy Listening
2023-12-17T15:00:00+01:00 - 2023-12-17T17:00:00+01:00 New Age
2023-12-17T17:00:00+01:00 - 2023-12-17T20:00:00+01:00 Lounge
2023-12-17T20:00:00+01:00 - 2023-12-17T22:00:00+01:00 House
2023-12-17T22:00:00+01:00 - 2023-12-18T00:00:00+01:00 Goa, Psytrance
```

**Comment by BusterNeece** [comment]
@Moonbase59 Found the code where if the start/end dates provided were equal, it would just return the default date range instead. Have done some work to make that more intuitive.

**Comment by Moonbase59** [comment]
@BusterNeece Yeah, seen that, thanks.

Only to get _today’s_ data doesn’t work yet:

Using

```python
start = "2023-12-17"
end = "2023-12-17"
```

or

```python
start = "2023-12-17T00:00:00+01:00"
end = "2023-12-17T23:59:00+01:00"
```

I get the last entry of 2023-12-16 and only the _first_ of 2023-12-17:

```
2023-12-16T18:00:00+01:00 - 2023-12-17T00:00:00+01:00 Heart Dance from London, UK
2023-12-17T00:00:00+01:00 - 2023-12-17T06:00:00+01:00 Nuit électronique
```

so _not_ the whole day as expected:

```
2023-12-17T00:00:00+01:00 - 2023-12-17T06:00:00+01:00 Nuit électronique
2023-12-17T06:00:00+01:00 - 2023-12-17T12:00:00+01:00 Pop
2023-12-17T06:00:00+01:00 - 2023-12-17T12:00:00+01:00 Schlager
2023-12-17T12:00:00+01:00 - 2023-12-17T15:00:00+01:00 Easy Listening
2023-12-17T15:00:00+01:00 - 2023-12-17T17:00:00+01:00 New Age
2023-12-17T17:00:00+01:00 - 2023-12-17T20:00:00+01:00 Lounge
2023-12-17T20:00:00+01:00 - 2023-12-17T22:00:00+01:00 House
2023-12-17T22:00:00+01:00 - 2023-12-18T00:00:00+01:00 Goa, Psytrance
```

This is only in the result when I specify dates 2023-12-17 to 2023-12-18.

**Comment by BusterNeece** [comment]
@Moonbase59 Should be better about that now.

**Comment by Moonbase59** [comment]
You actually only _use_ the date part, right? Looks good now! Thanks again!

See a chance we can also implement this playlist/schedule title/description thingy one of the days or are you booked out with all the other issues?

**Comment by BusterNeece** [comment]
@Moonbase59 Refresh my memory on that, where is it?

**Comment by Moonbase59** [comment]
Phew, let me find the pointers … found it:

- https://features.azuracast.com/suggestions/504596/add-epgcompatible-image-title-description-fields-to-playlists-and-schedules-for-
- https://github.com/Moonbase59/azuracast_xmltv/discussions/4#discussioncomment-7367202

**Comment by Moonbase59** [comment]
(Perfectly happy to wait a while longer if you’re overwhelmed with other work, or want to do the paid work first. Can’t really estimate how much extra work this would be.)

**Comment by BusterNeece** [comment]
@Moonbase59 It's on the longer term agenda, but it'll involve a DB migration and right now I'm trying to get in fixes that don't require DB changes.

**Comment by Moonbase59** [comment]
Ok, understand that. Just let me know "when" and we can talk it thorough, yes?

**Comment by Moonbase59** [comment]
Let’s close this as completed in the meantime. Thanks for another one!
