### ISSUE TITLE
Is NordPass compatible with Azuracast's Passkey authentication?

### ISSUE THREAD

**Issue by Axel12ok32** [AzuraCast/AzuraCast#6854]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.4

### What happened?

I am unable to configure Passkey authentication on my AzuraCast instance, using NordPass as a "wallet" to save and store all my passkeys and passwords in one place and shared across all my devices.

When I click on "Select Passkey," I get the NordPass window (with a prompt to create a new passkey), but when I then click on "add new passkey" the following error appears: `user not verified during authentication as from the image`.

Now, can anyone tell me if indeed, passkeys can be saved on the NordPass wallet? Or, is there an alternative, which is neither Windows Hello or browser passkeys?
![image (3)](https://github.com/AzuraCast/AzuraCast/assets/69150156/eaae97a7-b3e6-4986-adf5-7f712590a536)

**Comment by BusterNeece** [comment]
@Axel12ok32 Just as a follow-up to this issue (see #6893), apparently it's fairly widespread that some browsers don't properly send things over when logging in, so while we can enforce user verification on key registration (setup), we can't really enforce it on login, though we also don't necessarily need to at that point.

I've pushed a fix for this up to our Rolling Release branch. If you're able to update, I'd recommend doing so and confirming that this fixes using NordPass for passkeys.

**Comment by Axel12ok32** [comment]
Sorry to reopen this issue after a while. I have changed password managers and have not checked the problem again.
However, even after the stable update 0.20.2 (and the rolling release branch) I still cannot configure passkeys with NordPass, still giving the same problem.

Currently, the only way to use passkeys is to use other external managers (e.g., bitwarden and others) or the password manager of your own operating system.

**Comment by BusterNeece** [comment]
@Axel12ok32 Do you see any errors in the browser console when prompted to save a passkey? I'm not sure how NordPass differs from, say, Bitwarden or the OS-level passkey registration (both of which I can confirm work).
