### ISSUE TITLE
Failed to load because no supported source was found. (Due to the nowplaying task)

### ISSUE THREAD

**Issue by carlojou** [AzuraCast/AzuraCast#7158]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#432de15 (2024-05-22 16:35)

### What happened?

Hello,

We're constantly running into a bug where the public pages in AzuraCast just go "offline" despite the station running. This prevents the audio play button from working. When the play button is clicked on the following error pops up in the browsers console:

`Uncaught (in promise) DOMException: Failed to load because no supported source was found.`

I do suspect this is due to the nowplaying process being delayed/behind and not catching up so somehow this breaks the UI. I did submit a issue regarding the nowplaying delay in https://github.com/AzuraCast/AzuraCast/issues/6426 but it was never fixed and now it's also preventing the public pages from working.

Running the now playing process on the particular station fixes it almost immediately and then the album cover pops up and you can play the radio station again.

I would like to stress that the direct audio links work fine and do play if you visit their URL directly, its basically just the public page that stops functioning completely.

It looks like this when it's not functioning:

https://prnt.sc/gJPozgwBpvGM

I have tried all sorts of things, increasing sync time/etc but nothing works to fix it. The "now playing" updates is a long-standing issue with AzuraCast and larger installations, it just seems to be making things much worse now with it taking the public pages offline with it.

Thank you!

EDIT:

The now playing log is also flooded with the following text:

[2024-05-30T06:20:28.706378+00:00] AzuraCast.ERROR: Could not obtain lock for task "redacted"; skipping it. [] []
[2024-05-30T06:20:28.796468+00:00] AzuraCast.ERROR: Could not obtain lock for task "redacted"; skipping it. [] []
[2024-05-30T06:20:28.956644+00:00] AzuraCast.ERROR: Could not obtain lock for task "redacted"; skipping it. [] []
[2024-05-30T06:20:29.207020+00:00] AzuraCast.ERROR: Could not obtain lock for task "redacted"; skipping it. [] []
[2024-05-30T06:20:29.230429+00:00] AzuraCast.ERROR: Could not obtain lock for task "redacted"; skipping it. [] []
[2024-05-30T06:20:29.457349+00:00] AzuraCast.ERROR: Could not obtain lock for task "redacted"; skipping it. [] []
[2024-05-30T06:20:29.536497+00:00] AzuraCast.ERROR: Could not obtain lock for task "redacted"; skipping it. [] []

Going to the now playing API URL (/api/nowplaying/station_name) produces:

{"code":404,"type":"Error","message":"Record not found","formatted_message":"Record not found","extra_data":[],"success":false}

**Comment by BusterNeece** [comment]
@carlojou It looks like your Now Playing process is running into some sort of timeout or lock issue. Do you have remote relays that it can't connect to? If you manually run the Now Playing process, what does it say in response? How long does it take?

We've updated the Now Playing task queue process significantly in recent years to be more robust to this kind of thing, but if the individual process is timing out like that despite our best efforts, it may be thinking the station's offline just because of that.

**Comment by carlojou** [comment]
@BusterNeece I cannot really tell, these are nodes with quite a number of stations. (~80+).

If I run it manually for the station it works. If I run it for the entire server it does take quite some time (Would estimate around 4-8 minutes)

Looking at the now playing log the only other log I can see is:

[2024-05-30T16:21:40.222534+00:00] AzuraCast.ERROR: The EntityManager is closed.
[2024-05-30T16:21:52.380309+00:00] AzuraCast.ERROR: NowPlaying adapter error: The EntityManager is closed.

Rest are just "Could not obtain lock.."

Its not on a specific station either, seems like its happening on all of them.

My main concern is that the public page just stops working due to it, can we not include the audio URL on the public page play link regardless of the now-playing status? I would imagine thats the quickest fix, as fixing the now-playing issue does seem a lot more complex.

Thanks for your time as always!

**Comment by BusterNeece** [comment]
@carlojou 

> these are nodes with quite a number of stations. (~80+).

Yeah...AzuraCast doesn't tend to do well with, nor is it designed for, this kinda jam-packed reseller-ish hosting environment where CPU cycles are at a premium and all the processes are basically fighting each other.

I'll look into why the "Offline" station isn't listing streams, as it still should be regardless of online/offline status.

But my understanding from the vast majority of users is that AzuraCast's now-playing system works quite well on healthy, uncrowded installations. Without any further information on the specific HTTP requests triggering this, I have to assume it's just an overcrowding situation.

**Comment by BusterNeece** [comment]
We do support multi-station setups. We've done a *lot* of work to improve concurrency and handling of larger installations. But there's a difference between 10 stations on an installation and 80.

I don't have enough information here to know what's specifically causing this problem, so I can't even tell you what we're doing wrong in the first place here, let alone fix it.

**Comment by carlojou** [comment]
Let me know if there's any logs/etc you'd like to have a look at and ill forward it through. Commands you want me to run, etc and I can do so.

I do think the best way regardless is just to get the public page functioning even if the now-playing API does not work and then perhaps I can submit more information on the now playing issue.

**Comment by BusterNeece** [comment]
@carlojou I spun up a station that specifically occasionally went "offline" just to test things, and I immediately found a JavaScript error that, once triggered, basically "stuck" the station in an offline state, preventing it from loading correctly even when it came back online later on.

I pushed a fix for this up to the latest Rolling Release; let me know if this improves the situation for you. It may not remove every situation where the station reports as being offline when it's really online, but it should at least permit playback even in that state.

**Comment by carlojou** [comment]
@BusterNeece Appreciate it! I just upgraded to test this out but unfortunately that source issue is still present that causes the audio not to be able to be played:

`Uncaught (in promise) DOMException: Failed to load because no supported source was found.`

This error pops up in the browser's console log when clicking on the play button on the public page. 

The station looks like this when it happens, you don't see any default album cover or anything: https://prnt.sc/gJPozgwBpvGM

**Comment by BusterNeece** [comment]
@carlojou Are there any other console errors preceding that on the page? I looked at it and as far as I can tell even the "Station Offline" Now Playing data still properly includes the stream URL.

**Comment by carlojou** [comment]
I only see this other one:

 
`GET https://xxx/api/nowplaying/test_station 404 (Not Found)`

**Comment by BusterNeece** [comment]
@carlojou Ah, I think I see what's happening. If the timeouts pile on enough, as they seem to be doing here, then the Now Playing cache will completely expire and then it'll show up as a 404 when trying to fetch its Now Playing data.

We should probably check for this specific situation...if a station _actually exists_ but has no cached Now Playing data, we should fill up its cache entry with an offline entry (complete with stream details), so that streams are still available. Or we can just greatly extend the lifespan of the cache to try to mitigate this.

I'm not quite sure why your Now Playing process is timing out. I'd want to see a "Run Now Playing" for the station in question to see what its log output is.

**Comment by carlojou** [comment]
If I run the now playing task on the station it fixes it almost immediately on the public page and then the album cover pops up and your able to play the audio again.

Ill include the output for you:

Final NowPlaying Response for Station
id
68
name
"Test Station"
np
{"currentSong":{"text":"Shirley Murdock - Go on Without You","title":"Go on Without You","artist":"Shirley Murdock"},"listeners":{"total":0,"unique":0},"meta":{"online":true,"bitrate":192,"format":"audio/mpeg"},"clients":[]}

`response
"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\" ?><SHOUTCASTSERVER><CURRENTLISTENERS>0</CURRENTLISTENERS><PEAKLISTENERS>1</PEAKLISTENERS><MAXLISTENERS>99999</MAXLISTENERS><UNIQUELISTENERS>0</UNIQUELISTENERS><AVERAGETIME>0</AVERAGETIME><SERVERGENRE>Test</SERVERGENRE><SERVERGENRE2></SERVERGENRE2><SERVERGENRE3></SERVERGENRE3><SERVERGENRE4></SERVERGENRE4><SERVERGENRE5></SERVERGENRE5><SERVERURL>https://www.teststation.com</SERVERURL><SERVERTITLE>Test Station</SERVERTITLE><SONGTITLE>Shirley Murdock - Go on Without You</SONGTITLE><STREAMHITS>22</STREAMHITS><STREAMSTATUS>1</STREAMSTATUS><BACKUPSTATUS>0</BACKUPSTATUS><STREAMLISTED>0</STREAMLISTED><STREAMLISTEDERROR>0</STREAMLISTEDERROR><STREAMSOURCE>127.0.0.1</STREAMSOURCE><STREAMPATH>/radio.mp3</STREAMPATH><STREAMUPTIME>3460</STREAMUPTIME><BITRATE>192</BITRATE><SAMPLERATE>44100</SAMPLERATE><CONTENT>audio/mpeg</CONTENT><VERSION>2.6.1.777 (posix(linux x64))</VERSION><LISTENERS></LISTENERS><SONGHISTORY><SONG><PLAYEDAT>1717140098</PLAYEDAT><TITLE>Shirley Murdock - Go on Without You</TITLE><METADATA><TIT2>Shirley Murdock - Go on Without You</TIT2></METADATA></SONG><SONG><PLAYEDAT>1717139891</PLAYEDAT><TITLE>Dan + Shay - Speechless</TITLE><METADATA><TIT2>Dan + Shay - Speechless</TIT2></METADATA></SONG><SONG><PLAYEDAT>1717139555</PLAYEDAT><TITLE>Xscape - Am I Dreamin&apos;</TITLE><METADATA><TIT2>Xscape - Am I Dreamin&apos;</TIT2></METADATA></SONG><SONG><PLAYEDAT>1717139265</PLAYEDAT><TITLE>Brian McKnight - One Last Cry</TITLE><METADATA><TIT2>Brian McKnight - One Last Cry</TIT2></METADATA></SONG><SONG><PLAYEDAT>1717138964</PLAYEDAT><TITLE>After 7 - Baby I&apos;m For Real (Natural High)</TITLE><METADATA><TIT2>After 7 - Baby I&apos;m For Real (Natural High)</TIT2></METADATA></SONG><SONG><PLAYEDAT>1717138723</PLAYEDAT><TITLE>R.Kelly - Forever</TITLE><METADATA><TIT2>R.Kelly - Forever</TIT2></METADATA></SONG><SONG><PLAYEDAT>1717138477</PLAYEDAT><TITLE>Kindred The Family Soul - Far Away</TITLE><METADATA><TIT2>Kindred The Family Soul - Far Away</TIT2></METADATA></SONG><SONG><PLAYEDAT>1717138213</PLAYEDAT><TITLE>Jon B. - I Ain&apos;t Going Out (Album Version)</TITLE><METADATA><TIT2>Jon B. - I Ain&apos;t Going Out (Album Version)</TIT2></METADATA></SONG><SONG><PLAYEDAT>1717137889</PLAYEDAT><TITLE>Glenn Jones - I&apos;ve Been Searchin&apos; (Nobody Like You)</TITLE><METADATA><TIT2>Glenn Jones - I&apos;ve Been Searchin&apos; (Nobody Like You)</TIT2></METADATA></SONG><SONG><PLAYEDAT>1717137626</PLAYEDAT><TITLE>Az Yet - Last Night</TITLE><METADATA><TIT2>Az Yet - Last Night</TIT2></METADATA></SONG><SONG><PLAYEDAT>1717137342</PLAYEDAT><TITLE>Bobby Brown - Rock Wit&apos;cha</TITLE><METADATA><TIT2>Bobby Brown - Rock Wit&apos;cha</TIT2></METADATA></SONG><SONG><PLAYEDAT>1717137075</PLAYEDAT><TITLE>Rome - I Belong To You (Every Time I See Your Face)</TITLE><METADATA><TIT2>Rome - I Belong To You (Every Time I See Your Face)</TIT2></METADATA></SONG><SONG><PLAYEDAT>1717136813</PLAYEDAT><TITLE>Xscape - My Little Secret</TITLE><METADATA><TIT2>Xscape - My Little Secret</TIT2></METADATA></SONG><SONG><PLAYEDAT>1717136813</PLAYEDAT><TITLE>AzuraCast.com - AzuraCast is Live!</TITLE><METADATA><TIT2>AzuraCast.com - AzuraCast is Live!</TIT2></METADATA></SONG></SONGHISTORY></SHOUTCASTSERVER>"`

**Comment by BusterNeece** [comment]
@carlojou Also, I'm not sure if you've already done this but have you updated `NOW_PLAYING_MAX_CONCURRENT_PROCESSES` in `azuracast.env`? By default we only have 5 simultaneous processes running for Now Playing, which could definitely cause you to fall behind in larger installations. You may want to try setting that as high as 20. It'll bump CPU usage up but it should result in much more responsive Now Playing data.

**Comment by carlojou** [comment]
Hello,

That setting unfortunately we've tried setting a while back (When it was first introduced). It doesn't really seem like it does anything - there are no changes at all to the way the now-playing process functions. That setting was created due to that other issue I opened last year (https://github.com/AzuraCast/AzuraCast/issues/6426 ). 

The current setting is set to 85 on this particular node, we notice no increase in CPU/etc whenever we do change it. We've even gone as high as 150 but no changes in the resources used as well as the now-playing API still functioning the same. So not sure if it's working as it should.

**Comment by BusterNeece** [comment]
@carlojou I made a minor change to the processing logic; it won't keep the lock thing from happening (the lock thing really _shouldn't_ be happening and right now I can't find any reason in the code why it would, but I'm still investigating) but it'll keep it from grinding things to a halt quite as much.

I'd also not actually set it to the total number of stations. I'd set it to something like 20, just so it isn't trying to spin up station after station after station all at once and can stagger them a little better.

**Comment by BusterNeece** [comment]
@carlojou Neeeever mind. I found a fairly significant problem. Should be significantly improved after this latest Rolling Release update deploys.

If this helps your situation, we'll push out a minor stable release just to address it, as it likely affects a LOT of stations.

**Comment by carlojou** [comment]
I pushed the update and things do seem a lot better. So far hasn't had that issue prior.

Going to monitor it for you, will report back.

Thank you so much.

**Comment by BusterNeece** [comment]
@carlojou I suspect this was causing a fair number of the reports we've been getting from larger installations regarding Now Playing information either falling very out of date or falling off entirely.

If things appear to be resolved on your end, feel free to close the issue. You may find that with the updated code, it's no longer necessary to tweak the environment variables (and indeed it may improve performance to leave them at their defaults).

**Comment by carlojou** [comment]
@BusterNeece This does seem to be fully resolved. That fix alone has had a cascading effect as well on other things that always did not function properly like stats generation/etc.

Will close this as resolved.

Thank you!
