### ISSUE TITLE
HLS streams not working in latest Rolling release

### ISSUE THREAD

**Issue by sb-200** [AzuraCast/AzuraCast#7845]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#8783383 (2025-04-10 14:26)

### What happened?

Hi there,

Since updating to the latest rolling release, I am having an issue with HLS on my streams, the audio is intermettant and only plays for a small second before going silent, let me know if you need any further information :) 

Thank you,

### Relevant log output

```shell

```

**Comment by BusterNeece** [comment]
@sb-200 We definitely need more information. If you could check the Liquidsoap log from your station's log viewer and let us know what that says, it might give us some extra details.

**Comment by sb-200** [comment]
> [@sb-200](https://github.com/sb-200) We definitely need more information. If you could check the Liquidsoap log from your station's log viewer and let us know what that says, it might give us some extra details.

Thanks Buster, logs added now

**Comment by wegGehamstert** [comment]
Hey, i got the same issue, sadly i cant provide any logs because i switched to stable after having this issue.

**Comment by LordHelmchen666** [comment]
Yes. Also have this in latest RR. Installed Liquidsoap 2.3.2 inside Docker, then there is no problem with HLS output. So seems to be an issue related to latest Liquidsoap RR.
Tried to debug but could not find an error.

**Comment by LordHelmchen666** [comment]
Opened an issue https://github.com/savonet/liquidsoap/issues/4461

**Comment by LordHelmchen666** [comment]
@sb-200 As temporary workaround you can set your aac_hifi to 96k. It seems encoding higher bitrates causes trouble at the moment.

**Comment by LordHelmchen666** [comment]
toots wrote it is fixed. Now we have  to wait for next Liquidsoap build. :)

**Comment by BusterNeece** [comment]
@LordHelmchen666 We've updated to the latest Rolling Release.

**Comment by LordHelmchen666** [comment]
@BusterNeece It is fixed. I updated two servers (production and backup), set aac_hifi back to 192k. Listened for five minutes without interruptions.

**Comment by sb-200** [comment]
tested for 8 hours and no issues now :)

**Comment by TRAPRADIO** [comment]
Since we updated to version 0.21.0, the HLS audio-only stream no longer works.
We have now updated to the latest version 0.22.0, but the problem has not been resolved! The encoder always returns the error message ‘Could not connect to the server’.

We do not use Liquidsoap.
We receive an audio stream to be retransmitted in HLS.

I also tried lowering the bitrate, but that did not resolve the issue.

Thank you.
