### ISSUE TITLE
Port not auto generaged

### ISSUE THREAD

**Issue by kevev** [AzuraCast/AzuraCast#841]
Broadcast ports are not auto-generated. Is this feature broken? Also the admin link is incorrect as it is missing the port. If I enter a port manually when crating the broadcast the port number shows in the URLs.

**Comment by SlvrEagle23** [comment]
@kevev This feature shouldn't be broken, no. I've been creating stations all day today and it's been automatically assigning ports to them on the fly.

You won't see the ports automatically assigned until you return to edit the station's profile again, or restart broadcasting to re-build the configuration for the station.

IF you continue to encounter the issue, it would be helpful to see screenshots or further details of the steps you're taking.

**Comment by kevev** [comment]
This only happens when creating a station and Disabling AutoDJ. When using LiquidSoap the auto-generated port is shown in the URL.

**Comment by kevev** [comment]
SlvrEagle23 were you able to replicate my issue?

**Comment by SlvrEagle23** [comment]
@kevev I will work on it as soon as I can. Dealing with some personal issues at the moment.

**Comment by kevev** [comment]
Understood.

**Comment by SlvrEagle23** [comment]
@kevev This should be fixed now. Sorry for the delay and thank you for your patience.

**Comment by williambatson** [comment]
I know this is an old post - but a recent Docker install on Ubuntu 18.04 and a re-install Docker on Ubuntu 16.04 has the same isssue -    Station created, broadcast enabled, DO NOT use liquidsoap (no auto DJ) -  tried Shoutcast and Icecast -  all my new stations are showing port 8000 in the URL.    I'm not getting new ports as i create stations.   If I enable liquidsoap.auto DJ -  then new ports are assigned, all is well.

**Comment by SlvrEagle23** [comment]
@williambatson I'll reopen and take a look. It should've been fixed back in December...

**Comment by kevev** [comment]
> I know this is an old post - but a recent Docker install on Ubuntu 18.04 and a re-install Docker on Ubuntu 16.04 has the same isssue - Station created, broadcast enabled, DO NOT use liquidsoap (no auto DJ) - tried Shoutcast and Icecast - all my new stations are showing port 8000 in the URL. I'm not getting new ports as i create stations. If I enable liquidsoap.auto DJ - then new ports are assigned, all is well.

Same here. The bug seems to be when autoDJ is disabled during creation of a station. Can we get this fixed please?

**Comment by williambatson** [comment]
I have had no choice but to create ALL new stations with auto DJ enabled & using Liquidsoap -   I know I'm consuming way more CPU and RAM than I should for a simple broadcast only station, but this problem remains an issue and the only way to keep the wheels on is to just enable AutoDJ and Liquidsoap on all new streams.    Ubuntu 16.04/Docker Install -  updated regularly to lateest versions - Would like to see this addresses as well.   Not a major deal, but would lighten my server load big time for streams used only for broadcast.   Thanks

**Comment by SlvrEagle23** [comment]
@kevev @williambatson Figured the problem out; it wasn't including the port numbers of stations that _either_ had Liquidsoap turned off _or_ Icecast/Shoutcast turned off. It should have been only excluding the frontend ports if the frontend was disabled and likewise for the backend.

**Comment by kevev** [comment]
Fixed! Thank You SlvEagle23! Also thank you for assisting me in Slack channel!
